//! Bulk operations for ApprovalStepTemplate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateApprovalStepTemplateDto;
use crate::application::service::ApprovalStepTemplateService;
use crate::domain::entity::ApprovalStepTemplate;

/// Bulk operation handler for ApprovalStepTemplate entities.
///
/// Wraps `ApprovalStepTemplateService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ApprovalStepTemplateBulkService = GenericBulkService<ApprovalStepTemplate, CreateApprovalStepTemplateDto, ApprovalStepTemplateService>;

// <<< CUSTOM
// END CUSTOM
