//! Bulk operations for ApprovalRequest entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateApprovalRequestDto;
use crate::application::service::ApprovalRequestService;
use crate::domain::entity::ApprovalRequest;

/// Bulk operation handler for ApprovalRequest entities.
///
/// Wraps `ApprovalRequestService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ApprovalRequestBulkService = GenericBulkService<ApprovalRequest, CreateApprovalRequestDto, ApprovalRequestService>;

// <<< CUSTOM
// END CUSTOM
