//! Bulk operations for ApprovalStep entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateApprovalStepDto;
use crate::application::service::ApprovalStepService;
use crate::domain::entity::ApprovalStep;

/// Bulk operation handler for ApprovalStep entities.
///
/// Wraps `ApprovalStepService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ApprovalStepBulkService = GenericBulkService<ApprovalStep, CreateApprovalStepDto, ApprovalStepService>;

// <<< CUSTOM
// END CUSTOM
