//! Bulk operations for ApprovalPolicy entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateApprovalPolicyDto;
use crate::application::service::ApprovalPolicyService;
use crate::domain::entity::ApprovalPolicy;

/// Bulk operation handler for ApprovalPolicy entities.
///
/// Wraps `ApprovalPolicyService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ApprovalPolicyBulkService = GenericBulkService<ApprovalPolicy, CreateApprovalPolicyDto, ApprovalPolicyService>;

// <<< CUSTOM
// END CUSTOM
