//! Bulk operations for Delegation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateDelegationDto;
use crate::application::service::DelegationService;
use crate::domain::entity::Delegation;

/// Bulk operation handler for Delegation entities.
///
/// Wraps `DelegationService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type DelegationBulkService = GenericBulkService<Delegation, CreateDelegationDto, DelegationService>;

// <<< CUSTOM
// END CUSTOM
