//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod approval_policy_bulk;
pub mod approval_request_bulk;
pub mod approval_step_bulk;
pub mod approval_step_template_bulk;
pub mod delegation_bulk;

pub use approval_policy_bulk::ApprovalPolicyBulkService;
pub use approval_request_bulk::ApprovalRequestBulkService;
pub use approval_step_bulk::ApprovalStepBulkService;
pub use approval_step_template_bulk::ApprovalStepTemplateBulkService;
pub use delegation_bulk::DelegationBulkService;

// <<< CUSTOM
// END CUSTOM
