//! ApprovalStepTemplate DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ApprovalStepTemplate;
use crate::domain::entity::ApproverKind;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ApprovalStepTemplate
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateApprovalStepTemplateDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "policy_id")]
    pub policy_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "step_no")]
    pub step_no: i32,
    #[serde(alias = "approver_kind")]
    pub approver_kind: ApproverKind,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "approver_ref"
    )]
    pub approver_ref: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sla_hours")]
    pub sla_hours: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "all_of")]
    pub all_of: Option<serde_json::Value>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ApprovalStepTemplate
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateApprovalStepTemplateDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "policy_id")]
    pub policy_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "step_no")]
    pub step_no: i32,
    #[serde(alias = "approver_kind")]
    pub approver_kind: ApproverKind,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "approver_ref"
    )]
    pub approver_ref: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sla_hours")]
    pub sla_hours: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "all_of")]
    pub all_of: Option<serde_json::Value>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ApprovalStepTemplate
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchApprovalStepTemplateDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "policy_id")]
    pub policy_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "step_no")]
    pub step_no: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "approver_kind")]
    pub approver_kind: Option<ApproverKind>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "approver_ref")]
    pub approver_ref: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "sla_hours")]
    pub sla_hours: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "all_of")]
    pub all_of: Option<serde_json::Value>,
}

impl PatchApprovalStepTemplateDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some()
            || self.policy_id.is_some()
            || self.step_no.is_some()
            || self.approver_kind.is_some()
            || self.approver_ref.is_some()
            || self.sla_hours.is_some()
            || self.all_of.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ApprovalStepTemplate entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApprovalStepTemplateResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub policy_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub step_no: i32,
    pub approver_kind: ApproverKind,
    pub approver_ref: Option<Uuid>,
    pub sla_hours: Option<i32>,
    pub all_of: Option<serde_json::Value>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ApprovalStepTemplate entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApprovalStepTemplateListResponseDto {
    /// List of items
    pub items: Vec<ApprovalStepTemplateResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ApprovalStepTemplateListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(
        items: Vec<ApprovalStepTemplateResponseDto>,
        total: u64,
        page: u32,
        per_page: u32,
    ) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApprovalStepTemplateSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub policy_id: Uuid,
    pub step_no: i32,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ApprovalStepTemplate> for ApprovalStepTemplateResponseDto {
    fn from(entity: ApprovalStepTemplate) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            policy_id: entity.policy_id,
            step_no: entity.step_no,
            approver_kind: entity.approver_kind,
            approver_ref: entity.approver_ref,
            sla_hours: entity.sla_hours,
            all_of: entity.all_of,
            metadata: entity.metadata,
        }
    }
}

impl From<ApprovalStepTemplate> for ApprovalStepTemplateSummaryDto {
    fn from(entity: ApprovalStepTemplate) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            policy_id: entity.policy_id,
            step_no: entity.step_no,
            created_at,
        }
    }
}

impl From<CreateApprovalStepTemplateDto> for ApprovalStepTemplate {
    fn from(dto: CreateApprovalStepTemplateDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            policy_id: dto.policy_id,
            step_no: dto.step_no,
            approver_kind: dto.approver_kind,
            approver_ref: dto.approver_ref,
            sla_hours: dto.sla_hours,
            all_of: dto.all_of,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ApprovalStepTemplate> for ApprovalStepTemplateResponseDto {
    fn from(entity: &ApprovalStepTemplate) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            policy_id: entity.policy_id.clone(),
            step_no: entity.step_no.clone(),
            approver_kind: entity.approver_kind.clone(),
            approver_ref: entity.approver_ref.clone(),
            sla_hours: entity.sla_hours.clone(),
            all_of: entity.all_of.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateApprovalStepTemplateDto> for ApprovalStepTemplate {
    fn from_create_dto(dto: CreateApprovalStepTemplateDto) -> backbone_core::ServiceResult<Self> {
        Ok(ApprovalStepTemplate::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateApprovalStepTemplateDto> for ApprovalStepTemplate {
    fn apply_update(
        mut self,
        dto: UpdateApprovalStepTemplateDto,
    ) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.policy_id = dto.policy_id;
        self.step_no = dto.step_no;
        self.approver_kind = dto.approver_kind;
        self.approver_ref = dto.approver_ref;
        self.sla_hours = dto.sla_hours;
        self.all_of = dto.all_of;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ApprovalStepTemplate here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
