//! ApprovalPolicy DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ApprovalPolicy;
use crate::domain::entity::ApprovalResourceType;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ApprovalPolicy
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateApprovalPolicyDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(alias = "resource_type")]
    pub resource_type: ApprovalResourceType,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ApprovalPolicy
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateApprovalPolicyDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(alias = "resource_type")]
    pub resource_type: ApprovalResourceType,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ApprovalPolicy
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchApprovalPolicyDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "resource_type")]
    pub resource_type: Option<ApprovalResourceType>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl PatchApprovalPolicyDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some()
            || self.resource_type.is_some()
            || self.name.is_some()
            || self.is_active.is_some()
            || self.description.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ApprovalPolicy entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApprovalPolicyResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub company_id: Uuid,
    pub resource_type: ApprovalResourceType,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    pub description: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ApprovalPolicy entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApprovalPolicyListResponseDto {
    /// List of items
    pub items: Vec<ApprovalPolicyResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ApprovalPolicyListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(
        items: Vec<ApprovalPolicyResponseDto>,
        total: u64,
        page: u32,
        per_page: u32,
    ) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApprovalPolicySummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub resource_type: ApprovalResourceType,
    pub name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ApprovalPolicy> for ApprovalPolicyResponseDto {
    fn from(entity: ApprovalPolicy) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            resource_type: entity.resource_type,
            name: entity.name,
            is_active: entity.is_active,
            description: entity.description,
            metadata: entity.metadata,
        }
    }
}

impl From<ApprovalPolicy> for ApprovalPolicySummaryDto {
    fn from(entity: ApprovalPolicy) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            resource_type: entity.resource_type,
            name: entity.name,
            created_at,
        }
    }
}

impl From<CreateApprovalPolicyDto> for ApprovalPolicy {
    fn from(dto: CreateApprovalPolicyDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            resource_type: dto.resource_type,
            name: dto.name,
            is_active: dto.is_active,
            description: dto.description,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ApprovalPolicy> for ApprovalPolicyResponseDto {
    fn from(entity: &ApprovalPolicy) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            resource_type: entity.resource_type.clone(),
            name: entity.name.clone(),
            is_active: entity.is_active.clone(),
            description: entity.description.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateApprovalPolicyDto> for ApprovalPolicy {
    fn from_create_dto(dto: CreateApprovalPolicyDto) -> backbone_core::ServiceResult<Self> {
        Ok(ApprovalPolicy::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateApprovalPolicyDto> for ApprovalPolicy {
    fn apply_update(mut self, dto: UpdateApprovalPolicyDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.resource_type = dto.resource_type;
        self.name = dto.name;
        self.is_active = dto.is_active;
        self.description = dto.description;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ApprovalPolicy here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
