//! ApprovalStep DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ApprovalStep;
use crate::domain::entity::ApprovalStepStatus;
use crate::domain::entity::ApproverKind;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ApprovalStep
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateApprovalStepDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "request_id")]
    pub request_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "step_no")]
    pub step_no: i32,
    #[serde(alias = "approver_kind")]
    pub approver_kind: ApproverKind,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "approver_ref"
    )]
    pub approver_ref: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "assigned_to")]
    pub assigned_to: Uuid,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "delegated_from"
    )]
    pub delegated_from: Option<Uuid>,
    pub status: ApprovalStepStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "acted_at")]
    pub acted_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sla_due_at")]
    pub sla_due_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ApprovalStep
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateApprovalStepDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "request_id")]
    pub request_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "step_no")]
    pub step_no: i32,
    #[serde(alias = "approver_kind")]
    pub approver_kind: ApproverKind,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "approver_ref"
    )]
    pub approver_ref: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "assigned_to")]
    pub assigned_to: Uuid,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "delegated_from"
    )]
    pub delegated_from: Option<Uuid>,
    pub status: ApprovalStepStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "acted_at")]
    pub acted_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sla_due_at")]
    pub sla_due_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ApprovalStep
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchApprovalStepDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "request_id")]
    pub request_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "step_no")]
    pub step_no: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "approver_kind")]
    pub approver_kind: Option<ApproverKind>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "approver_ref")]
    pub approver_ref: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "assigned_to")]
    pub assigned_to: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "delegated_from")]
    pub delegated_from: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<ApprovalStepStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "acted_at")]
    pub acted_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "sla_due_at")]
    pub sla_due_at: Option<DateTime<Utc>>,
}

impl PatchApprovalStepDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some()
            || self.request_id.is_some()
            || self.step_no.is_some()
            || self.approver_kind.is_some()
            || self.approver_ref.is_some()
            || self.assigned_to.is_some()
            || self.delegated_from.is_some()
            || self.status.is_some()
            || self.acted_at.is_some()
            || self.comment.is_some()
            || self.sla_due_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ApprovalStep entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApprovalStepResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub request_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub step_no: i32,
    pub approver_kind: ApproverKind,
    pub approver_ref: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub assigned_to: Uuid,
    pub delegated_from: Option<Uuid>,
    pub status: ApprovalStepStatus,
    pub acted_at: Option<DateTime<Utc>>,
    pub comment: Option<String>,
    pub sla_due_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ApprovalStep entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApprovalStepListResponseDto {
    /// List of items
    pub items: Vec<ApprovalStepResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ApprovalStepListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ApprovalStepResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApprovalStepSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub request_id: Uuid,
    pub step_no: i32,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ApprovalStep> for ApprovalStepResponseDto {
    fn from(entity: ApprovalStep) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            request_id: entity.request_id,
            step_no: entity.step_no,
            approver_kind: entity.approver_kind,
            approver_ref: entity.approver_ref,
            assigned_to: entity.assigned_to,
            delegated_from: entity.delegated_from,
            status: entity.status,
            acted_at: entity.acted_at,
            comment: entity.comment,
            sla_due_at: entity.sla_due_at,
            metadata: entity.metadata,
        }
    }
}

impl From<ApprovalStep> for ApprovalStepSummaryDto {
    fn from(entity: ApprovalStep) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            request_id: entity.request_id,
            step_no: entity.step_no,
            created_at,
        }
    }
}

impl From<CreateApprovalStepDto> for ApprovalStep {
    fn from(dto: CreateApprovalStepDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            request_id: dto.request_id,
            step_no: dto.step_no,
            approver_kind: dto.approver_kind,
            approver_ref: dto.approver_ref,
            assigned_to: dto.assigned_to,
            delegated_from: dto.delegated_from,
            status: dto.status,
            acted_at: dto.acted_at,
            comment: dto.comment,
            sla_due_at: dto.sla_due_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ApprovalStep> for ApprovalStepResponseDto {
    fn from(entity: &ApprovalStep) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            request_id: entity.request_id.clone(),
            step_no: entity.step_no.clone(),
            approver_kind: entity.approver_kind.clone(),
            approver_ref: entity.approver_ref.clone(),
            assigned_to: entity.assigned_to.clone(),
            delegated_from: entity.delegated_from.clone(),
            status: entity.status.clone(),
            acted_at: entity.acted_at.clone(),
            comment: entity.comment.clone(),
            sla_due_at: entity.sla_due_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateApprovalStepDto> for ApprovalStep {
    fn from_create_dto(dto: CreateApprovalStepDto) -> backbone_core::ServiceResult<Self> {
        Ok(ApprovalStep::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateApprovalStepDto> for ApprovalStep {
    fn apply_update(mut self, dto: UpdateApprovalStepDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.request_id = dto.request_id;
        self.step_no = dto.step_no;
        self.approver_kind = dto.approver_kind;
        self.approver_ref = dto.approver_ref;
        self.assigned_to = dto.assigned_to;
        self.delegated_from = dto.delegated_from;
        self.status = dto.status;
        self.acted_at = dto.acted_at;
        self.comment = dto.comment;
        self.sla_due_at = dto.sla_due_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ApprovalStep here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
