//! ApprovalRequest DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ApprovalRequest;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::ApprovalPriority;
use crate::domain::entity::ApprovalResourceType;
use crate::domain::entity::ApprovalStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ApprovalRequest
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateApprovalRequestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(alias = "resource_type")]
    pub resource_type: ApprovalResourceType,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "resource_id")]
    pub resource_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "policy_id")]
    pub policy_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "requested_by")]
    pub requested_by: Uuid,
    pub status: ApprovalStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "current_step")]
    pub current_step: Option<i32>,
    pub priority: ApprovalPriority,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "submitted_at")]
    pub submitted_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "decided_at")]
    pub decided_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "decided_by")]
    pub decided_by: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<serde_json::Value>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ApprovalRequest
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateApprovalRequestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(alias = "resource_type")]
    pub resource_type: ApprovalResourceType,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "resource_id")]
    pub resource_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "policy_id")]
    pub policy_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "requested_by")]
    pub requested_by: Uuid,
    pub status: ApprovalStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "current_step")]
    pub current_step: Option<i32>,
    pub priority: ApprovalPriority,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "submitted_at")]
    pub submitted_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "decided_at")]
    pub decided_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "decided_by")]
    pub decided_by: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<serde_json::Value>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ApprovalRequest
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchApprovalRequestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "resource_type")]
    pub resource_type: Option<ApprovalResourceType>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "resource_id")]
    pub resource_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "policy_id")]
    pub policy_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "requested_by")]
    pub requested_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<ApprovalStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "current_step")]
    pub current_step: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub priority: Option<ApprovalPriority>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "submitted_at")]
    pub submitted_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "decided_at")]
    pub decided_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "decided_by")]
    pub decided_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<serde_json::Value>,
}

impl PatchApprovalRequestDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.resource_type.is_some() || self.resource_id.is_some() || self.policy_id.is_some() || self.requested_by.is_some() || self.status.is_some() || self.current_step.is_some() || self.priority.is_some() || self.submitted_at.is_some() || self.decided_at.is_some() || self.decided_by.is_some() || self.summary.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ApprovalRequest entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApprovalRequestResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub resource_type: ApprovalResourceType,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub resource_id: Uuid,
    pub policy_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub requested_by: Uuid,
    pub status: ApprovalStatus,
    pub current_step: Option<i32>,
    pub priority: ApprovalPriority,
    pub submitted_at: Option<DateTime<Utc>>,
    pub decided_at: Option<DateTime<Utc>>,
    pub decided_by: Option<Uuid>,
    pub summary: Option<serde_json::Value>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ApprovalRequest entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApprovalRequestListResponseDto {
    /// List of items
    pub items: Vec<ApprovalRequestResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ApprovalRequestListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ApprovalRequestResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApprovalRequestSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub resource_type: ApprovalResourceType,
    pub resource_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ApprovalRequest> for ApprovalRequestResponseDto {
    fn from(entity: ApprovalRequest) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            resource_type: entity.resource_type,
            resource_id: entity.resource_id,
            policy_id: entity.policy_id,
            requested_by: entity.requested_by,
            status: entity.status,
            current_step: entity.current_step,
            priority: entity.priority,
            submitted_at: entity.submitted_at,
            decided_at: entity.decided_at,
            decided_by: entity.decided_by,
            summary: entity.summary,
            metadata: entity.metadata,
        }
    }
}

impl From<ApprovalRequest> for ApprovalRequestSummaryDto {
    fn from(entity: ApprovalRequest) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            resource_type: entity.resource_type,
            resource_id: entity.resource_id,
            created_at,
        }
    }
}

impl From<CreateApprovalRequestDto> for ApprovalRequest {
    fn from(dto: CreateApprovalRequestDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            resource_type: dto.resource_type,
            resource_id: dto.resource_id,
            policy_id: dto.policy_id,
            requested_by: dto.requested_by,
            status: dto.status,
            current_step: dto.current_step,
            priority: dto.priority,
            submitted_at: dto.submitted_at,
            decided_at: dto.decided_at,
            decided_by: dto.decided_by,
            summary: dto.summary,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ApprovalRequest> for ApprovalRequestResponseDto {
    fn from(entity: &ApprovalRequest) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            resource_type: entity.resource_type.clone(),
            resource_id: entity.resource_id.clone(),
            policy_id: entity.policy_id.clone(),
            requested_by: entity.requested_by.clone(),
            status: entity.status.clone(),
            current_step: entity.current_step.clone(),
            priority: entity.priority.clone(),
            submitted_at: entity.submitted_at.clone(),
            decided_at: entity.decided_at.clone(),
            decided_by: entity.decided_by.clone(),
            summary: entity.summary.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateApprovalRequestDto> for ApprovalRequest {
    fn from_create_dto(dto: CreateApprovalRequestDto) -> backbone_core::ServiceResult<Self> {
        Ok(ApprovalRequest::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateApprovalRequestDto> for ApprovalRequest {
    fn apply_update(mut self, dto: UpdateApprovalRequestDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.resource_type = dto.resource_type;
        self.resource_id = dto.resource_id;
        self.policy_id = dto.policy_id;
        self.requested_by = dto.requested_by;
        self.status = dto.status;
        self.current_step = dto.current_step;
        self.priority = dto.priority;
        self.submitted_at = dto.submitted_at;
        self.decided_at = dto.decided_at;
        self.decided_by = dto.decided_by;
        self.summary = dto.summary;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ApprovalRequest here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
