//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{AndSpecification, NotSpecification, OrSpecification, Specification};

pub mod approval_policy_specification;
pub mod approval_request_specification;
pub mod approval_step_specification;
pub mod approval_step_template_specification;
pub mod delegation_specification;

// <<< CUSTOM
// END CUSTOM
