//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod approval_policy_domain_policy;
pub mod approval_request_domain_policy;
pub mod approval_step_domain_policy;
pub mod approval_step_template_domain_policy;
pub mod delegation_domain_policy;

pub use approval_policy_domain_policy::ApprovalPolicyDomainPolicy;
pub use approval_request_domain_policy::ApprovalRequestDomainPolicy;
pub use approval_step_domain_policy::ApprovalStepDomainPolicy;
pub use approval_step_template_domain_policy::ApprovalStepTemplateDomainPolicy;
pub use delegation_domain_policy::DelegationDomainPolicy;

// <<< CUSTOM
// END CUSTOM
