//! Application service for ApprovalStepTemplate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `approval_step_template_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::domain::entity::ApprovalStepTemplate;
use crate::infrastructure::persistence::ApprovalStepTemplateRepository;
use crate::presentation::dto::{CreateApprovalStepTemplateDto, UpdateApprovalStepTemplateDto};

/// Application service for ApprovalStepTemplate entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `approval_step_template_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ApprovalStepTemplateServiceCustom {
///     inner: Arc<ApprovalStepTemplateService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ApprovalStepTemplateService = GenericCrudService<
    ApprovalStepTemplate,
    CreateApprovalStepTemplateDto,
    UpdateApprovalStepTemplateDto,
    ApprovalStepTemplateRepository,
>;

// <<< CUSTOM
// END CUSTOM
