//! Application service for ApprovalStep entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `approval_step_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateApprovalStepDto, UpdateApprovalStepDto};
use crate::domain::entity::ApprovalStep;
use crate::infrastructure::persistence::ApprovalStepRepository;

/// Application service for ApprovalStep entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `approval_step_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ApprovalStepServiceCustom {
///     inner: Arc<ApprovalStepService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ApprovalStepService = GenericCrudService<
    ApprovalStep,
    CreateApprovalStepDto,
    UpdateApprovalStepDto,
    ApprovalStepRepository,
>;

// <<< CUSTOM
// END CUSTOM
