//! Application service for Delegation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `delegation_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::domain::entity::Delegation;
use crate::infrastructure::persistence::DelegationRepository;
use crate::presentation::dto::{CreateDelegationDto, UpdateDelegationDto};

/// Application service for Delegation entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `delegation_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct DelegationServiceCustom {
///     inner: Arc<DelegationService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type DelegationService =
    GenericCrudService<Delegation, CreateDelegationDto, UpdateDelegationDto, DelegationRepository>;

// <<< CUSTOM
// END CUSTOM
