//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod approval_policy_service;
pub mod approval_request_service;
pub mod approval_step_service;
pub mod approval_step_template_service;
pub mod delegation_service;

// <<< CUSTOM
// END CUSTOM

pub use approval_policy_service::ApprovalPolicyService;
pub use approval_request_service::ApprovalRequestService;
pub use approval_step_service::ApprovalStepService;
pub use approval_step_template_service::ApprovalStepTemplateService;
pub use delegation_service::DelegationService;
// <<< CUSTOM
// END CUSTOM
