-- ApprovalRequest Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the approvals.approval_requests table.
-- Customize this file to add your initial data.

-- INSERT INTO approvals.approval_requests (
--     id,
--     company_id,
--     resource_type,
--     resource_id,
--     policy_id,
--     requested_by,
--     status,
--     current_step,
--     priority,
--     submitted_at,
--     decided_at,
--     decided_by,
--     summary,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO approvals.approval_requests (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

