-- ApprovalStepTemplate Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the approvals.approval_step_templates table.
-- Customize this file to add your initial data.

-- INSERT INTO approvals.approval_step_templates (
--     id,
--     company_id,
--     policy_id,
--     step_no,
--     approver_kind,
--     approver_ref,
--     sla_hours,
--     all_of,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO approvals.approval_step_templates (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

