-- ApprovalPolicy Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the approvals.approval_policies table.
-- Customize this file to add your initial data.

-- INSERT INTO approvals.approval_policies (
--     id,
--     company_id,
--     resource_type,
--     name,
--     status,
--     description,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO approvals.approval_policies (id, code, name, status, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

