-- ApprovalStep Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the approvals.approval_steps table.
-- Customize this file to add your initial data.

-- INSERT INTO approvals.approval_steps (
--     id,
--     company_id,
--     request_id,
--     step_no,
--     approver_kind,
--     assigned_to,
--     delegated_from,
--     status,
--     acted_at,
--     comment,
--     sla_due_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO approvals.approval_steps (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

