-- Migration: Create approval_steps table
-- Generated by metaphor-schema

-- Create approver_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approver_kind') THEN
        CREATE TYPE approver_kind AS ENUM ('specific_employee', 'manager_of_requester', 'department_head', 'role', 'position');
    END IF;
END
$$;

-- Create approval_step_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approval_step_status') THEN
        CREATE TYPE approval_step_status AS ENUM ('pending', 'approved', 'rejected', 'delegated', 'skipped', 'escalated');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS approvals;

CREATE TABLE IF NOT EXISTS approvals.approval_steps (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    request_id UUID NOT NULL,
    step_no INTEGER NOT NULL,
    approver_kind approver_kind NOT NULL,
    assigned_to UUID NOT NULL,
    delegated_from UUID,
    status approval_step_status NOT NULL DEFAULT 'pending',
    acted_at TIMESTAMPTZ,
    comment TEXT,
    sla_due_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_approval_steps_request_id ON approvals.approval_steps (request_id);

CREATE INDEX IF NOT EXISTS idx_approval_steps_assigned_to_status ON approvals.approval_steps (assigned_to, status);

CREATE UNIQUE INDEX IF NOT EXISTS idx_approval_steps_request_id_step_no ON approvals.approval_steps (request_id, step_no) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_approval_steps_metadata_gin ON approvals.approval_steps USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_approval_steps_metadata_deleted_at ON approvals.approval_steps ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_approval_steps_metadata_created_at ON approvals.approval_steps ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_approval_steps_metadata_updated_at ON approvals.approval_steps ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION approvals.approval_steps_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS approval_steps_insert_audit ON approvals.approval_steps;
CREATE TRIGGER approval_steps_insert_audit BEFORE INSERT ON approvals.approval_steps
    FOR EACH ROW EXECUTE FUNCTION approvals.approval_steps_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS approval_steps_update_audit ON approvals.approval_steps;
CREATE TRIGGER approval_steps_update_audit BEFORE UPDATE ON approvals.approval_steps
    FOR EACH ROW EXECUTE FUNCTION approvals.approval_steps_audit_timestamp();
