-- Company fence posture for approvals module (ADR-0014: strict)
-- Generated by metaphor-schema. Every entity here carries company_id and is fenced
-- strict: a session sees only rows whose company_id equals the request-scoped
-- company (`set_config('app.company_id', <uuid>, true)`); an unset var sees zero
-- rows (fail-closed). These tables shipped company_id without a policy since the
-- pre-ADR-0014 policy cleanup; this migration installs the declared fence
-- (Wave 1 P0 sweep, 2026-08-16). Requires the app to connect as a non-superuser
-- role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for approvals.approval_policies
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE approvals.approval_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE approvals.approval_policies FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS approval_policies_company_isolation ON approvals.approval_policies;
CREATE POLICY approval_policies_company_isolation ON approvals.approval_policies
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for approvals.approval_requests
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE approvals.approval_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE approvals.approval_requests FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS approval_requests_company_isolation ON approvals.approval_requests;
CREATE POLICY approval_requests_company_isolation ON approvals.approval_requests
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for approvals.approval_step_templates
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE approvals.approval_step_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE approvals.approval_step_templates FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS approval_step_templates_company_isolation ON approvals.approval_step_templates;
CREATE POLICY approval_step_templates_company_isolation ON approvals.approval_step_templates
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for approvals.approval_steps
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE approvals.approval_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE approvals.approval_steps FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS approval_steps_company_isolation ON approvals.approval_steps;
CREATE POLICY approval_steps_company_isolation ON approvals.approval_steps
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for approvals.delegations
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE approvals.delegations ENABLE ROW LEVEL SECURITY;
ALTER TABLE approvals.delegations FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS delegations_company_isolation ON approvals.delegations;
CREATE POLICY delegations_company_isolation ON approvals.delegations
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);
