-- Audit Triggers Migration for approvals module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: ApprovalPolicy (approvals.approval_policies)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION approvals.approval_policies_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS approval_policies_insert_audit ON approvals.approval_policies;
CREATE TRIGGER approval_policies_insert_audit BEFORE INSERT ON approvals.approval_policies
    FOR EACH ROW EXECUTE FUNCTION approvals.approval_policies_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS approval_policies_update_audit ON approvals.approval_policies;
CREATE TRIGGER approval_policies_update_audit BEFORE UPDATE ON approvals.approval_policies
    FOR EACH ROW EXECUTE FUNCTION approvals.approval_policies_audit_timestamp();

-- ==============================================================================
-- Table: ApprovalRequest (approvals.approval_requests)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION approvals.approval_requests_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS approval_requests_insert_audit ON approvals.approval_requests;
CREATE TRIGGER approval_requests_insert_audit BEFORE INSERT ON approvals.approval_requests
    FOR EACH ROW EXECUTE FUNCTION approvals.approval_requests_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS approval_requests_update_audit ON approvals.approval_requests;
CREATE TRIGGER approval_requests_update_audit BEFORE UPDATE ON approvals.approval_requests
    FOR EACH ROW EXECUTE FUNCTION approvals.approval_requests_audit_timestamp();

-- ==============================================================================
-- Table: ApprovalStep (approvals.approval_steps)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION approvals.approval_steps_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS approval_steps_insert_audit ON approvals.approval_steps;
CREATE TRIGGER approval_steps_insert_audit BEFORE INSERT ON approvals.approval_steps
    FOR EACH ROW EXECUTE FUNCTION approvals.approval_steps_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS approval_steps_update_audit ON approvals.approval_steps;
CREATE TRIGGER approval_steps_update_audit BEFORE UPDATE ON approvals.approval_steps
    FOR EACH ROW EXECUTE FUNCTION approvals.approval_steps_audit_timestamp();

-- ==============================================================================
-- Table: ApprovalStepTemplate (approvals.approval_step_templates)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION approvals.approval_step_templates_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS approval_step_templates_insert_audit ON approvals.approval_step_templates;
CREATE TRIGGER approval_step_templates_insert_audit BEFORE INSERT ON approvals.approval_step_templates
    FOR EACH ROW EXECUTE FUNCTION approvals.approval_step_templates_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS approval_step_templates_update_audit ON approvals.approval_step_templates;
CREATE TRIGGER approval_step_templates_update_audit BEFORE UPDATE ON approvals.approval_step_templates
    FOR EACH ROW EXECUTE FUNCTION approvals.approval_step_templates_audit_timestamp();

-- ==============================================================================
-- Table: Delegation (approvals.delegations)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION approvals.delegations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS delegations_insert_audit ON approvals.delegations;
CREATE TRIGGER delegations_insert_audit BEFORE INSERT ON approvals.delegations
    FOR EACH ROW EXECUTE FUNCTION approvals.delegations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS delegations_update_audit ON approvals.delegations;
CREATE TRIGGER delegations_update_audit BEFORE UPDATE ON approvals.delegations
    FOR EACH ROW EXECUTE FUNCTION approvals.delegations_audit_timestamp();

