-- Enum types for approvals module
-- Generated by metaphor-schema

-- Create approval_resource_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approval_resource_type') THEN
        CREATE TYPE approval_resource_type AS ENUM ('promotion', 'onboarding', 'onboarding_task', 'offboarding', 'clearance', 'leave', 'timesheet', 'offer', 'appraisal', 'custom');
    END IF;
END
$$;

-- Create approval_priority enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approval_priority') THEN
        CREATE TYPE approval_priority AS ENUM ('low', 'normal', 'high', 'urgent');
    END IF;
END
$$;

-- Create approval_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approval_status') THEN
        CREATE TYPE approval_status AS ENUM ('draft', 'pending', 'approved', 'rejected', 'withdrawn', 'cancelled');
    END IF;
END
$$;

-- Create approval_step_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approval_step_status') THEN
        CREATE TYPE approval_step_status AS ENUM ('pending', 'approved', 'rejected', 'delegated', 'skipped', 'escalated');
    END IF;
END
$$;

-- Create approver_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approver_kind') THEN
        CREATE TYPE approver_kind AS ENUM ('specific_employee', 'manager_of_requester', 'department_head', 'role', 'position');
    END IF;
END
$$;

-- Create delegation_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'delegation_status') THEN
        CREATE TYPE delegation_status AS ENUM ('active', 'revoked');
    END IF;
END
$$;

