-- Migration: Create approval_requests table
-- Generated by metaphor-schema

-- Create approval_resource_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approval_resource_type') THEN
        CREATE TYPE approval_resource_type AS ENUM ('promotion', 'onboarding', 'onboarding_task', 'offboarding', 'clearance', 'leave', 'timesheet', 'offer', 'appraisal', 'custom');
    END IF;
END
$$;

-- Create approval_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approval_status') THEN
        CREATE TYPE approval_status AS ENUM ('draft', 'pending', 'approved', 'rejected', 'withdrawn', 'cancelled');
    END IF;
END
$$;

-- Create approval_priority enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approval_priority') THEN
        CREATE TYPE approval_priority AS ENUM ('low', 'normal', 'high', 'urgent');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS approvals;

CREATE TABLE IF NOT EXISTS approvals.approval_requests (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    resource_type approval_resource_type NOT NULL,
    resource_id UUID NOT NULL,
    policy_id UUID,
    requested_by UUID NOT NULL,
    status approval_status NOT NULL DEFAULT 'draft',
    current_step INTEGER,
    priority approval_priority NOT NULL DEFAULT 'normal',
    submitted_at TIMESTAMPTZ,
    decided_at TIMESTAMPTZ,
    decided_by UUID,
    summary JSONB,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_approval_requests_company_id_status ON approvals.approval_requests (company_id, status);

CREATE INDEX IF NOT EXISTS idx_approval_requests_requested_by ON approvals.approval_requests (requested_by);

CREATE INDEX IF NOT EXISTS idx_approval_requests_resource_type_resource_id ON approvals.approval_requests (resource_type, resource_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_approval_requests_company_id_resource_type_resource_id ON approvals.approval_requests (company_id, resource_type, resource_id) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_approval_requests_metadata_gin ON approvals.approval_requests USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_approval_requests_metadata_deleted_at ON approvals.approval_requests ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_approval_requests_metadata_created_at ON approvals.approval_requests ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_approval_requests_metadata_updated_at ON approvals.approval_requests ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION approvals.approval_requests_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS approval_requests_insert_audit ON approvals.approval_requests;
CREATE TRIGGER approval_requests_insert_audit BEFORE INSERT ON approvals.approval_requests
    FOR EACH ROW EXECUTE FUNCTION approvals.approval_requests_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS approval_requests_update_audit ON approvals.approval_requests;
CREATE TRIGGER approval_requests_update_audit BEFORE UPDATE ON approvals.approval_requests
    FOR EACH ROW EXECUTE FUNCTION approvals.approval_requests_audit_timestamp();
