-- Migration: Create approval_step_templates table
-- Generated by metaphor-schema

-- Create approver_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approver_kind') THEN
        CREATE TYPE approver_kind AS ENUM ('specific_employee', 'manager_of_requester', 'department_head', 'role', 'position');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS approvals;

CREATE TABLE IF NOT EXISTS approvals.approval_step_templates (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    policy_id UUID NOT NULL,
    step_no INTEGER NOT NULL,
    approver_kind approver_kind NOT NULL,
    approver_ref UUID,
    sla_hours INTEGER,
    all_of JSONB,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_approval_step_templates_policy_id ON approvals.approval_step_templates (policy_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_approval_step_templates_policy_id_step_no ON approvals.approval_step_templates (policy_id, step_no) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_approval_step_templates_metadata_gin ON approvals.approval_step_templates USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_approval_step_templates_metadata_deleted_at ON approvals.approval_step_templates ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_approval_step_templates_metadata_created_at ON approvals.approval_step_templates ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_approval_step_templates_metadata_updated_at ON approvals.approval_step_templates ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION approvals.approval_step_templates_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS approval_step_templates_insert_audit ON approvals.approval_step_templates;
CREATE TRIGGER approval_step_templates_insert_audit BEFORE INSERT ON approvals.approval_step_templates
    FOR EACH ROW EXECUTE FUNCTION approvals.approval_step_templates_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS approval_step_templates_update_audit ON approvals.approval_step_templates;
CREATE TRIGGER approval_step_templates_update_audit BEFORE UPDATE ON approvals.approval_step_templates
    FOR EACH ROW EXECUTE FUNCTION approvals.approval_step_templates_audit_timestamp();
