-- Migration: Create approval_policies table
-- Generated by metaphor-schema

-- Create approval_resource_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approval_resource_type') THEN
        CREATE TYPE approval_resource_type AS ENUM ('promotion', 'onboarding', 'onboarding_task', 'offboarding', 'clearance', 'leave', 'timesheet', 'offer', 'appraisal', 'custom');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS approvals;

CREATE TABLE IF NOT EXISTS approvals.approval_policies (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    resource_type approval_resource_type NOT NULL,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    description TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_approval_policies_company_id ON approvals.approval_policies (company_id);

CREATE INDEX IF NOT EXISTS idx_approval_policies_company_id_resource_type ON approvals.approval_policies (company_id, resource_type);

CREATE UNIQUE INDEX IF NOT EXISTS idx_approval_policies_company_id_resource_type_name ON approvals.approval_policies (company_id, resource_type, name) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_approval_policies_metadata_gin ON approvals.approval_policies USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_approval_policies_metadata_deleted_at ON approvals.approval_policies ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_approval_policies_metadata_created_at ON approvals.approval_policies ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_approval_policies_metadata_updated_at ON approvals.approval_policies ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION approvals.approval_policies_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS approval_policies_insert_audit ON approvals.approval_policies;
CREATE TRIGGER approval_policies_insert_audit BEFORE INSERT ON approvals.approval_policies
    FOR EACH ROW EXECUTE FUNCTION approvals.approval_policies_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS approval_policies_update_audit ON approvals.approval_policies;
CREATE TRIGGER approval_policies_update_audit BEFORE UPDATE ON approvals.approval_policies
    FOR EACH ROW EXECUTE FUNCTION approvals.approval_policies_audit_timestamp();
