//! Domain events for ApprovalRequest entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ApprovalRequest;

/// Domain events for ApprovalRequest — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ApprovalRequest>)` variant.
pub type ApprovalRequestEvent = CrudEvent<ApprovalRequest>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ApprovalRequest events.
pub type ApprovalRequestEventPublisher = Arc<dyn CrudEventPublisher<ApprovalRequest> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopApprovalRequestEventPublisher = NoOpCrudEventPublisher<ApprovalRequest>;
