//! Event handler trait for ApprovalStep events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ApprovalStepEvent;

/// Event handler for ApprovalStep events.
/// Implement this trait to react to ApprovalStep lifecycle events.
pub trait ApprovalStepEventHandler: EventHandler<ApprovalStepEvent> {}
