//! Event handler trait for ApprovalPolicy events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ApprovalPolicyEvent;

/// Event handler for ApprovalPolicy events.
/// Implement this trait to react to ApprovalPolicy lifecycle events.
pub trait ApprovalPolicyEventHandler: EventHandler<ApprovalPolicyEvent> {}
