//! Domain events for ApprovalStepTemplate entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ApprovalStepTemplate;

/// Domain events for ApprovalStepTemplate — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ApprovalStepTemplate>)` variant.
pub type ApprovalStepTemplateEvent = CrudEvent<ApprovalStepTemplate>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ApprovalStepTemplate events.
pub type ApprovalStepTemplateEventPublisher = Arc<dyn CrudEventPublisher<ApprovalStepTemplate> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopApprovalStepTemplateEventPublisher = NoOpCrudEventPublisher<ApprovalStepTemplate>;
