//! Event handler trait for ApprovalStepTemplate events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::ApprovalStepTemplateEvent;
use backbone_messaging::EventHandler;

/// Event handler for ApprovalStepTemplate events.
/// Implement this trait to react to ApprovalStepTemplate lifecycle events.
pub trait ApprovalStepTemplateEventHandler: EventHandler<ApprovalStepTemplateEvent> {}
