//! Domain events for ApprovalPolicy entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ApprovalPolicy;

/// Domain events for ApprovalPolicy — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ApprovalPolicy>)` variant.
pub type ApprovalPolicyEvent = CrudEvent<ApprovalPolicy>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ApprovalPolicy events.
pub type ApprovalPolicyEventPublisher = Arc<dyn CrudEventPublisher<ApprovalPolicy> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopApprovalPolicyEventPublisher = NoOpCrudEventPublisher<ApprovalPolicy>;
