//! Event handler trait for ApprovalRequest events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ApprovalRequestEvent;

/// Event handler for ApprovalRequest events.
/// Implement this trait to react to ApprovalRequest lifecycle events.
pub trait ApprovalRequestEventHandler: EventHandler<ApprovalRequestEvent> {}
