//! Domain events for ApprovalStep entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ApprovalStep;

/// Domain events for ApprovalStep — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ApprovalStep>)` variant.
pub type ApprovalStepEvent = CrudEvent<ApprovalStep>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ApprovalStep events.
pub type ApprovalStepEventPublisher = Arc<dyn CrudEventPublisher<ApprovalStep> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopApprovalStepEventPublisher = NoOpCrudEventPublisher<ApprovalStep>;
