//! Domain events for Delegation entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Delegation;

/// Domain events for Delegation — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Delegation>)` variant.
pub type DelegationEvent = CrudEvent<Delegation>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Delegation events.
pub type DelegationEventPublisher = Arc<dyn CrudEventPublisher<Delegation> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopDelegationEventPublisher = NoOpCrudEventPublisher<Delegation>;
