//! Event handler trait for Delegation events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::DelegationEvent;

/// Event handler for Delegation events.
/// Implement this trait to react to Delegation lifecycle events.
pub trait DelegationEventHandler: EventHandler<DelegationEvent> {}
