//! ApprovalRequest seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ApprovalRequest data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// APPROVALREQUEST SEEDER
// ============================================================================

/// Seeder for approval_request
pub struct SeedApprovalRequestSeeder;

impl SeedApprovalRequestSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedApprovalRequestSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedApprovalRequestSeeder {
    fn name(&self) -> &'static str {
        "SeedApprovalRequestSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if approvals.approval_requests table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM approvals.approval_requests")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/approval_request_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM approvals.approval_requests")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
