//! ApprovalStep seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ApprovalStep data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// APPROVALSTEP SEEDER
// ============================================================================

/// Seeder for approval_step
pub struct SeedApprovalStepSeeder;

impl SeedApprovalStepSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedApprovalStepSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedApprovalStepSeeder {
    fn name(&self) -> &'static str {
        "SeedApprovalStepSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if approvals.approval_steps table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM approvals.approval_steps")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/approval_step_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM approvals.approval_steps")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

