//! Repository trait for ApprovalPolicy aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ApprovalPolicy aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::{ApprovalPolicy, ApprovalResourceType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ApprovalPolicyPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ApprovalPolicyPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ApprovalPolicyPaginatedResult {
    pub data: Vec<ApprovalPolicy>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ApprovalPolicyFilter {
    pub company_id: Option<Uuid>,
    pub resource_type: Option<ApprovalResourceType>,
    pub name: Option<String>,
    pub is_active: Option<bool>,
    pub description: Option<String>,
}

impl ApprovalPolicyFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some()
            || self.resource_type.is_some()
            || self.name.is_some()
            || self.is_active.is_some()
            || self.description.is_some()
    }
}

/// Repository trait for ApprovalPolicy aggregate
///
/// This trait defines the persistence contract for ApprovalPolicy entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ApprovalPolicyRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new approval_policy entity
    async fn save(&self, entity: &ApprovalPolicy) -> Result<ApprovalPolicy>;

    /// Find approval_policy by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ApprovalPolicy>>;

    /// Find all approval_policy entities
    async fn find_all(&self) -> Result<Vec<ApprovalPolicy>>;

    /// Update approval_policy by ID
    async fn update(&self, id: &str, entity: &ApprovalPolicy) -> Result<Option<ApprovalPolicy>>;

    /// Delete approval_policy by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List approval_policy with pagination
    async fn list(
        &self,
        params: ApprovalPolicyPaginationParams,
    ) -> Result<ApprovalPolicyPaginatedResult>;

    /// List approval_policy with pagination and filters
    async fn list_with_filters(
        &self,
        params: ApprovalPolicyPaginationParams,
        filters: ApprovalPolicyFilter,
    ) -> Result<ApprovalPolicyPaginatedResult>;

    /// Count all approval_policy entities
    async fn count(&self) -> Result<u64>;

    /// Count approval_policy entities matching filters
    async fn count_with_filters(&self, filters: ApprovalPolicyFilter) -> Result<u64>;

    /// Check if approval_policy exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete approval_policy by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted approval_policy by ID
    async fn restore(&self, id: &str) -> Result<Option<ApprovalPolicy>>;

    /// List soft-deleted approval_policy entities
    async fn list_deleted(
        &self,
        params: ApprovalPolicyPaginationParams,
    ) -> Result<ApprovalPolicyPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save approval_policy entities
    async fn bulk_save(&self, entities: &[ApprovalPolicy]) -> Result<Vec<ApprovalPolicy>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
