//! Repository trait for ApprovalRequest aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ApprovalRequest aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{ApprovalRequest, ApprovalPriority, ApprovalResourceType, ApprovalStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ApprovalRequestPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ApprovalRequestPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ApprovalRequestPaginatedResult {
    pub data: Vec<ApprovalRequest>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ApprovalRequestFilter {
    pub company_id: Option<Uuid>,
    pub resource_type: Option<ApprovalResourceType>,
    pub resource_id: Option<Uuid>,
    pub policy_id: Option<Uuid>,
    pub requested_by: Option<Uuid>,
    pub status: Option<ApprovalStatus>,
    pub priority: Option<ApprovalPriority>,
    pub decided_by: Option<Uuid>,
}

impl ApprovalRequestFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.resource_type.is_some() || self.resource_id.is_some() || self.policy_id.is_some() || self.requested_by.is_some() || self.status.is_some() || self.priority.is_some() || self.decided_by.is_some()
    }
}

/// Repository trait for ApprovalRequest aggregate
///
/// This trait defines the persistence contract for ApprovalRequest entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ApprovalRequestRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new approval_request entity
    async fn save(&self, entity: &ApprovalRequest) -> Result<ApprovalRequest>;

    /// Find approval_request by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ApprovalRequest>>;

    /// Find all approval_request entities
    async fn find_all(&self) -> Result<Vec<ApprovalRequest>>;

    /// Update approval_request by ID
    async fn update(&self, id: &str, entity: &ApprovalRequest) -> Result<Option<ApprovalRequest>>;

    /// Delete approval_request by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List approval_request with pagination
    async fn list(&self, params: ApprovalRequestPaginationParams) -> Result<ApprovalRequestPaginatedResult>;

    /// List approval_request with pagination and filters
    async fn list_with_filters(&self, params: ApprovalRequestPaginationParams, filters: ApprovalRequestFilter) -> Result<ApprovalRequestPaginatedResult>;

    /// Count all approval_request entities
    async fn count(&self) -> Result<u64>;

    /// Count approval_request entities matching filters
    async fn count_with_filters(&self, filters: ApprovalRequestFilter) -> Result<u64>;

    /// Check if approval_request exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete approval_request by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted approval_request by ID
    async fn restore(&self, id: &str) -> Result<Option<ApprovalRequest>>;

    /// List soft-deleted approval_request entities
    async fn list_deleted(&self, params: ApprovalRequestPaginationParams) -> Result<ApprovalRequestPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save approval_request entities
    async fn bulk_save(&self, entities: &[ApprovalRequest]) -> Result<Vec<ApprovalRequest>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
