//! Repository trait for ApprovalStepTemplate aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ApprovalStepTemplate aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{ApprovalStepTemplate, ApproverKind};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ApprovalStepTemplatePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ApprovalStepTemplatePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ApprovalStepTemplatePaginatedResult {
    pub data: Vec<ApprovalStepTemplate>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ApprovalStepTemplateFilter {
    pub company_id: Option<Uuid>,
    pub policy_id: Option<Uuid>,
    pub approver_kind: Option<ApproverKind>,
    pub approver_ref: Option<Uuid>,
}

impl ApprovalStepTemplateFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.policy_id.is_some() || self.approver_kind.is_some() || self.approver_ref.is_some()
    }
}

/// Repository trait for ApprovalStepTemplate aggregate
///
/// This trait defines the persistence contract for ApprovalStepTemplate entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ApprovalStepTemplateRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new approval_step_template entity
    async fn save(&self, entity: &ApprovalStepTemplate) -> Result<ApprovalStepTemplate>;

    /// Find approval_step_template by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ApprovalStepTemplate>>;

    /// Find all approval_step_template entities
    async fn find_all(&self) -> Result<Vec<ApprovalStepTemplate>>;

    /// Update approval_step_template by ID
    async fn update(&self, id: &str, entity: &ApprovalStepTemplate) -> Result<Option<ApprovalStepTemplate>>;

    /// Delete approval_step_template by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List approval_step_template with pagination
    async fn list(&self, params: ApprovalStepTemplatePaginationParams) -> Result<ApprovalStepTemplatePaginatedResult>;

    /// List approval_step_template with pagination and filters
    async fn list_with_filters(&self, params: ApprovalStepTemplatePaginationParams, filters: ApprovalStepTemplateFilter) -> Result<ApprovalStepTemplatePaginatedResult>;

    /// Count all approval_step_template entities
    async fn count(&self) -> Result<u64>;

    /// Count approval_step_template entities matching filters
    async fn count_with_filters(&self, filters: ApprovalStepTemplateFilter) -> Result<u64>;

    /// Check if approval_step_template exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete approval_step_template by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted approval_step_template by ID
    async fn restore(&self, id: &str) -> Result<Option<ApprovalStepTemplate>>;

    /// List soft-deleted approval_step_template entities
    async fn list_deleted(&self, params: ApprovalStepTemplatePaginationParams) -> Result<ApprovalStepTemplatePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save approval_step_template entities
    async fn bulk_save(&self, entities: &[ApprovalStepTemplate]) -> Result<Vec<ApprovalStepTemplate>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
