//! Repository trait for ApprovalStep aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ApprovalStep aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{ApprovalStep, ApprovalStepStatus, ApproverKind};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ApprovalStepPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ApprovalStepPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ApprovalStepPaginatedResult {
    pub data: Vec<ApprovalStep>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ApprovalStepFilter {
    pub company_id: Option<Uuid>,
    pub request_id: Option<Uuid>,
    pub approver_kind: Option<ApproverKind>,
    pub approver_ref: Option<Uuid>,
    pub assigned_to: Option<Uuid>,
    pub delegated_from: Option<Uuid>,
    pub status: Option<ApprovalStepStatus>,
    pub comment: Option<String>,
}

impl ApprovalStepFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.request_id.is_some() || self.approver_kind.is_some() || self.approver_ref.is_some() || self.assigned_to.is_some() || self.delegated_from.is_some() || self.status.is_some() || self.comment.is_some()
    }
}

/// Repository trait for ApprovalStep aggregate
///
/// This trait defines the persistence contract for ApprovalStep entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ApprovalStepRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new approval_step entity
    async fn save(&self, entity: &ApprovalStep) -> Result<ApprovalStep>;

    /// Find approval_step by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ApprovalStep>>;

    /// Find all approval_step entities
    async fn find_all(&self) -> Result<Vec<ApprovalStep>>;

    /// Update approval_step by ID
    async fn update(&self, id: &str, entity: &ApprovalStep) -> Result<Option<ApprovalStep>>;

    /// Delete approval_step by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List approval_step with pagination
    async fn list(&self, params: ApprovalStepPaginationParams) -> Result<ApprovalStepPaginatedResult>;

    /// List approval_step with pagination and filters
    async fn list_with_filters(&self, params: ApprovalStepPaginationParams, filters: ApprovalStepFilter) -> Result<ApprovalStepPaginatedResult>;

    /// Count all approval_step entities
    async fn count(&self) -> Result<u64>;

    /// Count approval_step entities matching filters
    async fn count_with_filters(&self, filters: ApprovalStepFilter) -> Result<u64>;

    /// Check if approval_step exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete approval_step by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted approval_step by ID
    async fn restore(&self, id: &str) -> Result<Option<ApprovalStep>>;

    /// List soft-deleted approval_step entities
    async fn list_deleted(&self, params: ApprovalStepPaginationParams) -> Result<ApprovalStepPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save approval_step entities
    async fn bulk_save(&self, entities: &[ApprovalStep]) -> Result<Vec<ApprovalStep>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
