//! Repository trait for Delegation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Delegation aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::{Delegation, DelegationStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DelegationPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl DelegationPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct DelegationPaginatedResult {
    pub data: Vec<Delegation>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DelegationFilter {
    pub company_id: Option<Uuid>,
    pub approver_id: Option<Uuid>,
    pub delegate_to_id: Option<Uuid>,
    pub reason: Option<String>,
    pub status: Option<DelegationStatus>,
}

impl DelegationFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some()
            || self.approver_id.is_some()
            || self.delegate_to_id.is_some()
            || self.reason.is_some()
            || self.status.is_some()
    }
}

/// Repository trait for Delegation aggregate
///
/// This trait defines the persistence contract for Delegation entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait DelegationRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new delegation entity
    async fn save(&self, entity: &Delegation) -> Result<Delegation>;

    /// Find delegation by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Delegation>>;

    /// Find all delegation entities
    async fn find_all(&self) -> Result<Vec<Delegation>>;

    /// Update delegation by ID
    async fn update(&self, id: &str, entity: &Delegation) -> Result<Option<Delegation>>;

    /// Delete delegation by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List delegation with pagination
    async fn list(&self, params: DelegationPaginationParams) -> Result<DelegationPaginatedResult>;

    /// List delegation with pagination and filters
    async fn list_with_filters(
        &self,
        params: DelegationPaginationParams,
        filters: DelegationFilter,
    ) -> Result<DelegationPaginatedResult>;

    /// Count all delegation entities
    async fn count(&self) -> Result<u64>;

    /// Count delegation entities matching filters
    async fn count_with_filters(&self, filters: DelegationFilter) -> Result<u64>;

    /// Check if delegation exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete delegation by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted delegation by ID
    async fn restore(&self, id: &str) -> Result<Option<Delegation>>;

    /// List soft-deleted delegation entities
    async fn list_deleted(
        &self,
        params: DelegationPaginationParams,
    ) -> Result<DelegationPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save delegation entities
    async fn bulk_save(&self, entities: &[Delegation]) -> Result<Vec<Delegation>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
