//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.

pub mod approval_policy_repository;
pub mod approval_request_repository;
pub mod approval_step_repository;
pub mod approval_step_template_repository;
pub mod delegation_repository;

// Re-exports
pub use approval_policy_repository::{
    ApprovalPolicyFilter, ApprovalPolicyPaginatedResult, ApprovalPolicyPaginationParams,
    ApprovalPolicyRepository,
};
pub use approval_request_repository::{
    ApprovalRequestFilter, ApprovalRequestPaginatedResult, ApprovalRequestPaginationParams,
    ApprovalRequestRepository,
};
pub use approval_step_repository::{
    ApprovalStepFilter, ApprovalStepPaginatedResult, ApprovalStepPaginationParams,
    ApprovalStepRepository,
};
pub use approval_step_template_repository::{
    ApprovalStepTemplateFilter, ApprovalStepTemplatePaginatedResult,
    ApprovalStepTemplatePaginationParams, ApprovalStepTemplateRepository,
};
pub use delegation_repository::{
    DelegationFilter, DelegationPaginatedResult, DelegationPaginationParams, DelegationRepository,
};
