//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod approval_policy_repository;
pub mod approval_request_repository;
pub mod approval_step_repository;
pub mod approval_step_template_repository;
pub mod delegation_repository;

// Re-exports
pub use approval_policy_repository::{
    ApprovalPolicyRepository,
    ApprovalPolicyPaginationParams,
    ApprovalPolicyPaginatedResult,
    ApprovalPolicyFilter,
};
pub use approval_request_repository::{
    ApprovalRequestRepository,
    ApprovalRequestPaginationParams,
    ApprovalRequestPaginatedResult,
    ApprovalRequestFilter,
};
pub use approval_step_repository::{
    ApprovalStepRepository,
    ApprovalStepPaginationParams,
    ApprovalStepPaginatedResult,
    ApprovalStepFilter,
};
pub use approval_step_template_repository::{
    ApprovalStepTemplateRepository,
    ApprovalStepTemplatePaginationParams,
    ApprovalStepTemplatePaginatedResult,
    ApprovalStepTemplateFilter,
};
pub use delegation_repository::{
    DelegationRepository,
    DelegationPaginationParams,
    DelegationPaginatedResult,
    DelegationFilter,
};
