//! Repository for ApprovalStep entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ApprovalStep, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ApprovalStep;

/// Table name for ApprovalStep entities
pub const TABLE_NAME: &str = "approvals.approval_steps";

/// Repository for ApprovalStep entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ApprovalStepRepository(
    backbone_orm::GenericCrudRepository<ApprovalStep, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ApprovalStepRepository {
    type Target = backbone_orm::GenericCrudRepository<ApprovalStep, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ApprovalStepRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ApprovalStepRepository, ApprovalStep, soft_delete);
