//! Repository for ApprovalStepTemplate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ApprovalStepTemplate, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ApprovalStepTemplate;

/// Table name for ApprovalStepTemplate entities
pub const TABLE_NAME: &str = "approvals.approval_step_templates";

/// Repository for ApprovalStepTemplate entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ApprovalStepTemplateRepository(
    backbone_orm::GenericCrudRepository<ApprovalStepTemplate, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ApprovalStepTemplateRepository {
    type Target =
        backbone_orm::GenericCrudRepository<ApprovalStepTemplate, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl ApprovalStepTemplateRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(
    ApprovalStepTemplateRepository,
    ApprovalStepTemplate,
    soft_delete
);
