//! Repository for ApprovalPolicy entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ApprovalPolicy, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ApprovalPolicy;

/// Table name for ApprovalPolicy entities
pub const TABLE_NAME: &str = "approvals.approval_policies";

/// Repository for ApprovalPolicy entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ApprovalPolicyRepository(
    backbone_orm::GenericCrudRepository<ApprovalPolicy, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ApprovalPolicyRepository {
    type Target = backbone_orm::GenericCrudRepository<ApprovalPolicy, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl ApprovalPolicyRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ApprovalPolicyRepository, ApprovalPolicy, soft_delete);
