//! Repository for Delegation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Delegation, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Delegation;

/// Table name for Delegation entities
pub const TABLE_NAME: &str = "approvals.delegations";

/// Repository for Delegation entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct DelegationRepository(
    backbone_orm::GenericCrudRepository<Delegation, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for DelegationRepository {
    type Target = backbone_orm::GenericCrudRepository<Delegation, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl DelegationRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(DelegationRepository, Delegation, soft_delete);
