//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod approval_policy_repository;
mod approval_request_repository;
mod approval_step_repository;
mod approval_step_template_repository;
mod delegation_repository;

// Custom persistence modules
// <<< CUSTOM
// The decision engine's statements (hand-authored; see metaphor.codegen.yaml user_owned).
pub mod approvals_write_repository;
pub use approvals_write_repository::ApprovalsWriteRepository;
// END CUSTOM

// Re-exports
pub use approval_policy_repository::ApprovalPolicyRepository;
pub use approval_request_repository::ApprovalRequestRepository;
pub use approval_step_repository::ApprovalStepRepository;
pub use approval_step_template_repository::ApprovalStepTemplateRepository;
pub use delegation_repository::DelegationRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
