//! Validator for ApprovalStepTemplate entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ApprovalStepTemplate>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::ApprovalStepTemplate;

/// Validator type alias for ApprovalStepTemplate entities.
pub type ApprovalStepTemplateValidator = EntityValidator<ApprovalStepTemplate>;

/// Build a validator for ApprovalStepTemplate with all schema-defined field rules.
pub fn approval_step_template_validator() -> ApprovalStepTemplateValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
