//! Validator for ApprovalRequest entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ApprovalRequest>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::ApprovalRequest;

/// Validator type alias for ApprovalRequest entities.
pub type ApprovalRequestValidator = EntityValidator<ApprovalRequest>;

/// Build a validator for ApprovalRequest with all schema-defined field rules.
pub fn approval_request_validator() -> ApprovalRequestValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
