//! Validator for ApprovalPolicy entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ApprovalPolicy>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::ApprovalPolicy;

/// Validator type alias for ApprovalPolicy entities.
pub type ApprovalPolicyValidator = EntityValidator<ApprovalPolicy>;

/// Build a validator for ApprovalPolicy with all schema-defined field rules.
pub fn approval_policy_validator() -> ApprovalPolicyValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &ApprovalPolicy| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &ApprovalPolicy| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
