//! Auth configuration for ApprovalStep handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ApprovalStep>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ApprovalStepService;
use crate::domain::entity::ApprovalStep;

/// Permission string constants for ApprovalStep operations.
pub mod permissions {
    pub const LIST:        &str = "approval_step:list";
    pub const READ:        &str = "approval_step:read";
    pub const CREATE:      &str = "approval_step:create";
    pub const UPDATE:      &str = "approval_step:update";
    pub const DELETE:      &str = "approval_step:delete";
    pub const RESTORE:     &str = "approval_step:restore";
    pub const TRASH:       &str = "approval_step:trash";
    pub const EMPTY_TRASH: &str = "approval_step:empty_trash";
    pub const BULK_CREATE: &str = "approval_step:bulk_create";
    pub const UPSERT:      &str = "approval_step:upsert";
}

/// Resource policy for ApprovalStep — maps CRUD actions to permission strings.
pub struct ApprovalStepPolicy;

#[async_trait]
impl ResourcePolicy<ApprovalStep> for ApprovalStepPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ApprovalStep,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ApprovalStep handlers.
///
/// Wraps `ApprovalStepService` and checks `ApprovalStepPolicy` before delegating.
pub type ApprovalStepGuard = PermissionGuard<ApprovalStep>;

/// Service-integrated permission guard for ApprovalStep (for use in generated handlers).
pub type ApprovalStepServiceGuard = ServicePermissionGuard<ApprovalStep, ApprovalStepService, ApprovalStepPolicy>;

// <<< CUSTOM
// END CUSTOM
