//! Auth configuration for ApprovalPolicy handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ApprovalPolicy>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ApprovalPolicyService;
use crate::domain::entity::ApprovalPolicy;

/// Permission string constants for ApprovalPolicy operations.
pub mod permissions {
    pub const LIST:        &str = "approval_policy:list";
    pub const READ:        &str = "approval_policy:read";
    pub const CREATE:      &str = "approval_policy:create";
    pub const UPDATE:      &str = "approval_policy:update";
    pub const DELETE:      &str = "approval_policy:delete";
    pub const RESTORE:     &str = "approval_policy:restore";
    pub const TRASH:       &str = "approval_policy:trash";
    pub const EMPTY_TRASH: &str = "approval_policy:empty_trash";
    pub const BULK_CREATE: &str = "approval_policy:bulk_create";
    pub const UPSERT:      &str = "approval_policy:upsert";
}

/// Resource policy for ApprovalPolicy — maps CRUD actions to permission strings.
pub struct ApprovalPolicyPolicy;

#[async_trait]
impl ResourcePolicy<ApprovalPolicy> for ApprovalPolicyPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ApprovalPolicy,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ApprovalPolicy handlers.
///
/// Wraps `ApprovalPolicyService` and checks `ApprovalPolicyPolicy` before delegating.
pub type ApprovalPolicyGuard = PermissionGuard<ApprovalPolicy>;

/// Service-integrated permission guard for ApprovalPolicy (for use in generated handlers).
pub type ApprovalPolicyServiceGuard = ServicePermissionGuard<ApprovalPolicy, ApprovalPolicyService, ApprovalPolicyPolicy>;

// <<< CUSTOM
// END CUSTOM
