//! Auth configuration for ApprovalRequest handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ApprovalRequest>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ApprovalRequestService;
use crate::domain::entity::ApprovalRequest;

/// Permission string constants for ApprovalRequest operations.
pub mod permissions {
    pub const LIST:        &str = "approval_request:list";
    pub const READ:        &str = "approval_request:read";
    pub const CREATE:      &str = "approval_request:create";
    pub const UPDATE:      &str = "approval_request:update";
    pub const DELETE:      &str = "approval_request:delete";
    pub const RESTORE:     &str = "approval_request:restore";
    pub const TRASH:       &str = "approval_request:trash";
    pub const EMPTY_TRASH: &str = "approval_request:empty_trash";
    pub const BULK_CREATE: &str = "approval_request:bulk_create";
    pub const UPSERT:      &str = "approval_request:upsert";
}

/// Resource policy for ApprovalRequest — maps CRUD actions to permission strings.
pub struct ApprovalRequestPolicy;

#[async_trait]
impl ResourcePolicy<ApprovalRequest> for ApprovalRequestPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ApprovalRequest,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ApprovalRequest handlers.
///
/// Wraps `ApprovalRequestService` and checks `ApprovalRequestPolicy` before delegating.
pub type ApprovalRequestGuard = PermissionGuard<ApprovalRequest>;

/// Service-integrated permission guard for ApprovalRequest (for use in generated handlers).
pub type ApprovalRequestServiceGuard = ServicePermissionGuard<ApprovalRequest, ApprovalRequestService, ApprovalRequestPolicy>;

// <<< CUSTOM
// END CUSTOM
