//! Auth configuration for ApprovalStepTemplate handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ApprovalStepTemplate>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ApprovalStepTemplateService;
use crate::domain::entity::ApprovalStepTemplate;

/// Permission string constants for ApprovalStepTemplate operations.
pub mod permissions {
    pub const LIST:        &str = "approval_step_template:list";
    pub const READ:        &str = "approval_step_template:read";
    pub const CREATE:      &str = "approval_step_template:create";
    pub const UPDATE:      &str = "approval_step_template:update";
    pub const DELETE:      &str = "approval_step_template:delete";
    pub const RESTORE:     &str = "approval_step_template:restore";
    pub const TRASH:       &str = "approval_step_template:trash";
    pub const EMPTY_TRASH: &str = "approval_step_template:empty_trash";
    pub const BULK_CREATE: &str = "approval_step_template:bulk_create";
    pub const UPSERT:      &str = "approval_step_template:upsert";
}

/// Resource policy for ApprovalStepTemplate — maps CRUD actions to permission strings.
pub struct ApprovalStepTemplatePolicy;

#[async_trait]
impl ResourcePolicy<ApprovalStepTemplate> for ApprovalStepTemplatePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ApprovalStepTemplate,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ApprovalStepTemplate handlers.
///
/// Wraps `ApprovalStepTemplateService` and checks `ApprovalStepTemplatePolicy` before delegating.
pub type ApprovalStepTemplateGuard = PermissionGuard<ApprovalStepTemplate>;

/// Service-integrated permission guard for ApprovalStepTemplate (for use in generated handlers).
pub type ApprovalStepTemplateServiceGuard = ServicePermissionGuard<ApprovalStepTemplate, ApprovalStepTemplateService, ApprovalStepTemplatePolicy>;

// <<< CUSTOM
// END CUSTOM
