//! Auth configuration for Delegation handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Delegation>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::DelegationService;
use crate::domain::entity::Delegation;

/// Permission string constants for Delegation operations.
pub mod permissions {
    pub const LIST:        &str = "delegation:list";
    pub const READ:        &str = "delegation:read";
    pub const CREATE:      &str = "delegation:create";
    pub const UPDATE:      &str = "delegation:update";
    pub const DELETE:      &str = "delegation:delete";
    pub const RESTORE:     &str = "delegation:restore";
    pub const TRASH:       &str = "delegation:trash";
    pub const EMPTY_TRASH: &str = "delegation:empty_trash";
    pub const BULK_CREATE: &str = "delegation:bulk_create";
    pub const UPSERT:      &str = "delegation:upsert";
}

/// Resource policy for Delegation — maps CRUD actions to permission strings.
pub struct DelegationPolicy;

#[async_trait]
impl ResourcePolicy<Delegation> for DelegationPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Delegation,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Delegation handlers.
///
/// Wraps `DelegationService` and checks `DelegationPolicy` before delegating.
pub type DelegationGuard = PermissionGuard<Delegation>;

/// Service-integrated permission guard for Delegation (for use in generated handlers).
pub type DelegationServiceGuard = ServicePermissionGuard<Delegation, DelegationService, DelegationPolicy>;

// <<< CUSTOM
// END CUSTOM
