//! ApprovalStepTemplate API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ApprovalStepTemplate CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// APPROVALSTEPTEMPLATE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ApprovalStepTemplate
pub struct ApprovalStepTemplateTestData;

impl TestDataGenerator for ApprovalStepTemplateTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "policy_id": Uuid::new_v4().to_string(),
            "step_no": 1,
            "approver_kind": "specific_employee",
            "approver_ref": null,
            "sla_hours": null,
            "all_of": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "policy_id": Uuid::new_v4().to_string(),
            "step_no": 1,
            "approver_kind": "specific_employee",
            "approver_ref": null,
            "sla_hours": null,
            "all_of": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(
            api,
            "/api/v1/approval_policies",
            &super::approval_policy_api_test::ApprovalPolicyTestData,
        )
        .await
        {
            deps.push(("policy_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// APPROVALSTEPTEMPLATE API TEST
// ============================================================================

/// ApprovalStepTemplate API test suite
pub struct ApprovalStepTemplateApiTest {
    inner: GenericCrudTest<ApprovalStepTemplateTestData>,
}

impl ApprovalStepTemplateApiTest {
    pub fn new() -> Self {
        let mut config =
            CrudTestConfig::new("/api/v1/approval_step_templates", "ApprovalStepTemplate");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ApprovalStepTemplateTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ApprovalStepTemplateApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_approval_step_template_crud() {
        let mut test = ApprovalStepTemplateApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ApprovalStepTemplate specific tests here
// <<< CUSTOM TESTS END >>>
