//! ApprovalRequest API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ApprovalRequest CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// APPROVALREQUEST TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ApprovalRequest
pub struct ApprovalRequestTestData;

impl TestDataGenerator for ApprovalRequestTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "resource_type": "promotion",
            "resource_id": Uuid::new_v4().to_string(),
            "policy_id": null,
            "requested_by": Uuid::new_v4().to_string(),
            "status": "draft",
            "current_step": null,
            "priority": "low",
            "submitted_at": now,
            "decided_at": now,
            "decided_by": null,
            "summary": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "resource_type": "promotion",
            "resource_id": Uuid::new_v4().to_string(),
            "policy_id": null,
            "requested_by": Uuid::new_v4().to_string(),
            "status": "draft",
            "current_step": null,
            "priority": "low",
            "submitted_at": now,
            "decided_at": now,
            "decided_by": null,
            "summary": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// APPROVALREQUEST API TEST
// ============================================================================

/// ApprovalRequest API test suite
pub struct ApprovalRequestApiTest {
    inner: GenericCrudTest<ApprovalRequestTestData>,
}

impl ApprovalRequestApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/approval_requests", "ApprovalRequest");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ApprovalRequestTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ApprovalRequestApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_approval_request_crud() {
        let mut test = ApprovalRequestApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ApprovalRequest specific tests here
// <<< CUSTOM TESTS END >>>
