//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod approval_policy_api_test;
pub mod approval_request_api_test;
pub mod approval_step_api_test;
pub mod approval_step_template_api_test;
pub mod delegation_api_test;

// Re-exports for convenience
pub use approval_policy_api_test::*;
pub use approval_request_api_test::*;
pub use approval_step_api_test::*;
pub use approval_step_template_api_test::*;
pub use crud_test_base::*;
pub use delegation_api_test::*;
