//! Approvals Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::ApprovalPolicyService;
use crate::application::service::ApprovalRequestService;
use crate::application::service::ApprovalStepService;
use crate::application::service::ApprovalStepTemplateService;
use crate::application::service::DelegationService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// ApprovalPolicy service
    pub approval_policy_service: Arc<ApprovalPolicyService>,
    /// ApprovalRequest service
    pub approval_request_service: Arc<ApprovalRequestService>,
    /// ApprovalStep service
    pub approval_step_service: Arc<ApprovalStepService>,
    /// ApprovalStepTemplate service
    pub approval_step_template_service: Arc<ApprovalStepTemplateService>,
    /// Delegation service
    pub delegation_service: Arc<DelegationService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        approval_policy_service: Arc<ApprovalPolicyService>,
        approval_request_service: Arc<ApprovalRequestService>,
        approval_step_service: Arc<ApprovalStepService>,
        approval_step_template_service: Arc<ApprovalStepTemplateService>,
        delegation_service: Arc<DelegationService>
    ) -> Self {
        Self {
            approval_policy_service,
            approval_request_service,
            approval_step_service,
            approval_step_template_service,
            delegation_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::ApprovalsModule) -> Self {
        Self {
            approval_policy_service: module.approval_policy_service.clone(),
            approval_request_service: module.approval_request_service.clone(),
            approval_step_service: module.approval_step_service.clone(),
            approval_step_template_service: module.approval_step_template_service.clone(),
            delegation_service: module.delegation_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    approval_policy_service: Option<Arc<ApprovalPolicyService>>,
    approval_request_service: Option<Arc<ApprovalRequestService>>,
    approval_step_service: Option<Arc<ApprovalStepService>>,
    approval_step_template_service: Option<Arc<ApprovalStepTemplateService>>,
    delegation_service: Option<Arc<DelegationService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the ApprovalPolicy service.
    pub fn with_approval_policy_service(mut self, service: Arc<ApprovalPolicyService>) -> Self {
        self.approval_policy_service = Some(service);
        self
    }

    /// Set the ApprovalRequest service.
    pub fn with_approval_request_service(mut self, service: Arc<ApprovalRequestService>) -> Self {
        self.approval_request_service = Some(service);
        self
    }

    /// Set the ApprovalStep service.
    pub fn with_approval_step_service(mut self, service: Arc<ApprovalStepService>) -> Self {
        self.approval_step_service = Some(service);
        self
    }

    /// Set the ApprovalStepTemplate service.
    pub fn with_approval_step_template_service(mut self, service: Arc<ApprovalStepTemplateService>) -> Self {
        self.approval_step_template_service = Some(service);
        self
    }

    /// Set the Delegation service.
    pub fn with_delegation_service(mut self, service: Arc<DelegationService>) -> Self {
        self.delegation_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            approval_policy_service: self.approval_policy_service.expect("approval_policy_service is required"),
            approval_request_service: self.approval_request_service.expect("approval_request_service is required"),
            approval_step_service: self.approval_step_service.expect("approval_step_service is required"),
            approval_step_template_service: self.approval_step_template_service.expect("approval_step_template_service is required"),
            delegation_service: self.delegation_service.expect("delegation_service is required"),
        }
    }
}
