//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    approval_policy_handler::create_approval_policy_routes,
    approval_request_handler::create_approval_request_routes,
    approval_step_handler::create_approval_step_routes,
    approval_step_template_handler::create_approval_step_template_routes,
    delegation_handler::create_delegation_routes,
};

use crate::application::service::{
    ApprovalPolicyService,
    ApprovalRequestService,
    ApprovalStepService,
    ApprovalStepTemplateService,
    DelegationService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub approval_policy: Arc<ApprovalPolicyService>,
    pub approval_request: Arc<ApprovalRequestService>,
    pub approval_step: Arc<ApprovalStepService>,
    pub approval_step_template: Arc<ApprovalStepTemplateService>,
    pub delegation: Arc<DelegationService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // ApprovalPolicy routes (12 Backbone endpoints)
        .merge(create_approval_policy_routes(services.approval_policy))
        // ApprovalRequest routes (12 Backbone endpoints)
        .merge(create_approval_request_routes(services.approval_request))
        // ApprovalStep routes (12 Backbone endpoints)
        .merge(create_approval_step_routes(services.approval_step))
        // ApprovalStepTemplate routes (12 Backbone endpoints)
        .merge(create_approval_step_template_routes(services.approval_step_template))
        // Delegation routes (12 Backbone endpoints)
        .merge(create_delegation_routes(services.delegation))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn approval_policy_routes(service: Arc<ApprovalPolicyService>) -> Router {
        create_approval_policy_routes(service)
    }

    pub fn approval_request_routes(service: Arc<ApprovalRequestService>) -> Router {
        create_approval_request_routes(service)
    }

    pub fn approval_step_routes(service: Arc<ApprovalStepService>) -> Router {
        create_approval_step_routes(service)
    }

    pub fn approval_step_template_routes(service: Arc<ApprovalStepTemplateService>) -> Router {
        create_approval_step_template_routes(service)
    }

    pub fn delegation_routes(service: Arc<DelegationService>) -> Router {
        create_delegation_routes(service)
    }

}
