//! Public events for Approvals module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use super::types::*;

// ============================================================================
// APPROVALPOLICY EVENTS
// ============================================================================

/// Event published when a ApprovalPolicy is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalPolicyCreatedEvent {
    pub id: ApprovalPolicyId,
    pub data: ApprovalPolicyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ApprovalPolicy is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalPolicyUpdatedEvent {
    pub id: ApprovalPolicyId,
    pub data: ApprovalPolicyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ApprovalPolicy is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalPolicyDeletedEvent {
    pub id: ApprovalPolicyId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// APPROVALREQUEST EVENTS
// ============================================================================

/// Event published when a ApprovalRequest is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalRequestCreatedEvent {
    pub id: ApprovalRequestId,
    pub data: ApprovalRequestDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ApprovalRequest is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalRequestUpdatedEvent {
    pub id: ApprovalRequestId,
    pub data: ApprovalRequestDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ApprovalRequest is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalRequestDeletedEvent {
    pub id: ApprovalRequestId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// APPROVALSTEP EVENTS
// ============================================================================

/// Event published when a ApprovalStep is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalStepCreatedEvent {
    pub id: ApprovalStepId,
    pub data: ApprovalStepDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ApprovalStep is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalStepUpdatedEvent {
    pub id: ApprovalStepId,
    pub data: ApprovalStepDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ApprovalStep is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalStepDeletedEvent {
    pub id: ApprovalStepId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// APPROVALSTEPTEMPLATE EVENTS
// ============================================================================

/// Event published when a ApprovalStepTemplate is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalStepTemplateCreatedEvent {
    pub id: ApprovalStepTemplateId,
    pub data: ApprovalStepTemplateDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ApprovalStepTemplate is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalStepTemplateUpdatedEvent {
    pub id: ApprovalStepTemplateId,
    pub data: ApprovalStepTemplateDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ApprovalStepTemplate is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalStepTemplateDeletedEvent {
    pub id: ApprovalStepTemplateId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// DELEGATION EVENTS
// ============================================================================

/// Event published when a Delegation is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DelegationCreatedEvent {
    pub id: DelegationId,
    pub data: DelegationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Delegation is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DelegationUpdatedEvent {
    pub id: DelegationId,
    pub data: DelegationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Delegation is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DelegationDeletedEvent {
    pub id: DelegationId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Approvals module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ApprovalsEvent {
    ApprovalPolicyCreated(ApprovalPolicyCreatedEvent),
    ApprovalPolicyUpdated(ApprovalPolicyUpdatedEvent),
    ApprovalPolicyDeleted(ApprovalPolicyDeletedEvent),
    ApprovalRequestCreated(ApprovalRequestCreatedEvent),
    ApprovalRequestUpdated(ApprovalRequestUpdatedEvent),
    ApprovalRequestDeleted(ApprovalRequestDeletedEvent),
    ApprovalStepCreated(ApprovalStepCreatedEvent),
    ApprovalStepUpdated(ApprovalStepUpdatedEvent),
    ApprovalStepDeleted(ApprovalStepDeletedEvent),
    ApprovalStepTemplateCreated(ApprovalStepTemplateCreatedEvent),
    ApprovalStepTemplateUpdated(ApprovalStepTemplateUpdatedEvent),
    ApprovalStepTemplateDeleted(ApprovalStepTemplateDeletedEvent),
    DelegationCreated(DelegationCreatedEvent),
    DelegationUpdated(DelegationUpdatedEvent),
    DelegationDeleted(DelegationDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalsEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for ApprovalsEventMetadata {
    fn default() -> Self {
        Self {
            module: "approvals",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
