//! Approvals Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Approvals exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use approvals::exports::{ApprovalPolicyDto};
//! ```

mod events;
mod services;
mod types;

// Re-export all public types
pub use events::*;
pub use services::*;
pub use types::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `ApprovalPolicyDto` - Data transfer object for ApprovalPolicy
/// - `ApprovalPolicySummary` - Summary view of ApprovalPolicy
/// - `ApprovalPolicyId` - Type-safe ID wrapper
/// - `ApprovalRequestDto` - Data transfer object for ApprovalRequest
/// - `ApprovalRequestSummary` - Summary view of ApprovalRequest
/// - `ApprovalRequestId` - Type-safe ID wrapper
/// - `ApprovalStepDto` - Data transfer object for ApprovalStep
/// - `ApprovalStepSummary` - Summary view of ApprovalStep
/// - `ApprovalStepId` - Type-safe ID wrapper
/// - `ApprovalStepTemplateDto` - Data transfer object for ApprovalStepTemplate
/// - `ApprovalStepTemplateSummary` - Summary view of ApprovalStepTemplate
/// - `ApprovalStepTemplateId` - Type-safe ID wrapper
/// - `DelegationDto` - Data transfer object for Delegation
/// - `DelegationSummary` - Summary view of Delegation
/// - `DelegationId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `ApprovalPolicyCreatedEvent` - Published when ApprovalPolicy is created
/// - `ApprovalPolicyUpdatedEvent` - Published when ApprovalPolicy is updated
/// - `ApprovalPolicyDeletedEvent` - Published when ApprovalPolicy is deleted
/// - `ApprovalRequestCreatedEvent` - Published when ApprovalRequest is created
/// - `ApprovalRequestUpdatedEvent` - Published when ApprovalRequest is updated
/// - `ApprovalRequestDeletedEvent` - Published when ApprovalRequest is deleted
/// - `ApprovalStepCreatedEvent` - Published when ApprovalStep is created
/// - `ApprovalStepUpdatedEvent` - Published when ApprovalStep is updated
/// - `ApprovalStepDeletedEvent` - Published when ApprovalStep is deleted
/// - `ApprovalStepTemplateCreatedEvent` - Published when ApprovalStepTemplate is created
/// - `ApprovalStepTemplateUpdatedEvent` - Published when ApprovalStepTemplate is updated
/// - `ApprovalStepTemplateDeletedEvent` - Published when ApprovalStepTemplate is deleted
/// - `DelegationCreatedEvent` - Published when Delegation is created
/// - `DelegationUpdatedEvent` - Published when Delegation is updated
/// - `DelegationDeletedEvent` - Published when Delegation is deleted
pub struct ExportSummary;
