//! Public services for Approvals module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Approvals module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait ApprovalsQueryService: Send + Sync {
    /// Get ApprovalPolicy by ID
    async fn get_approval_policy(&self, id: ApprovalPolicyId) -> Result<Option<ApprovalPolicyDto>>;

    /// Get ApprovalPolicy summary by ID
    async fn get_approval_policy_summary(&self, id: ApprovalPolicyId) -> Result<Option<ApprovalPolicySummary>>;

    /// Check if ApprovalPolicy exists
    async fn approval_policy_exists(&self, id: ApprovalPolicyId) -> Result<bool>;

    /// Get ApprovalRequest by ID
    async fn get_approval_request(&self, id: ApprovalRequestId) -> Result<Option<ApprovalRequestDto>>;

    /// Get ApprovalRequest summary by ID
    async fn get_approval_request_summary(&self, id: ApprovalRequestId) -> Result<Option<ApprovalRequestSummary>>;

    /// Check if ApprovalRequest exists
    async fn approval_request_exists(&self, id: ApprovalRequestId) -> Result<bool>;

    /// Get ApprovalStep by ID
    async fn get_approval_step(&self, id: ApprovalStepId) -> Result<Option<ApprovalStepDto>>;

    /// Get ApprovalStep summary by ID
    async fn get_approval_step_summary(&self, id: ApprovalStepId) -> Result<Option<ApprovalStepSummary>>;

    /// Check if ApprovalStep exists
    async fn approval_step_exists(&self, id: ApprovalStepId) -> Result<bool>;

    /// Get ApprovalStepTemplate by ID
    async fn get_approval_step_template(&self, id: ApprovalStepTemplateId) -> Result<Option<ApprovalStepTemplateDto>>;

    /// Get ApprovalStepTemplate summary by ID
    async fn get_approval_step_template_summary(&self, id: ApprovalStepTemplateId) -> Result<Option<ApprovalStepTemplateSummary>>;

    /// Check if ApprovalStepTemplate exists
    async fn approval_step_template_exists(&self, id: ApprovalStepTemplateId) -> Result<bool>;

    /// Get Delegation by ID
    async fn get_delegation(&self, id: DelegationId) -> Result<Option<DelegationDto>>;

    /// Get Delegation summary by ID
    async fn get_delegation_summary(&self, id: DelegationId) -> Result<Option<DelegationSummary>>;

    /// Check if Delegation exists
    async fn delegation_exists(&self, id: DelegationId) -> Result<bool>;

}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
