//! Public types for Approvals module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use crate::domain::entity::*;
use chrono::{DateTime, NaiveDate, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ============================================================================
// APPROVALPOLICY TYPES
// ============================================================================

/// Type-safe ID for ApprovalPolicy
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ApprovalPolicyId(pub Uuid);

impl ApprovalPolicyId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ApprovalPolicyId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ApprovalPolicyId> for Uuid {
    fn from(id: ApprovalPolicyId) -> Self {
        id.0
    }
}

/// Data transfer object for ApprovalPolicy
///
/// This is the public representation of ApprovalPolicy for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalPolicyDto {
    pub id: ApprovalPolicyId,
    pub company_id: Uuid,
    pub resource_type: ApprovalResourceType,
    pub name: String,
    pub is_active: bool,
    pub description: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of ApprovalPolicy for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalPolicySummary {
    pub id: ApprovalPolicyId,
    pub name: String,
}

/// Reference to ApprovalPolicy for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalPolicyRef {
    pub id: ApprovalPolicyId,
}

// ============================================================================
// APPROVALREQUEST TYPES
// ============================================================================

/// Type-safe ID for ApprovalRequest
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ApprovalRequestId(pub Uuid);

impl ApprovalRequestId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ApprovalRequestId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ApprovalRequestId> for Uuid {
    fn from(id: ApprovalRequestId) -> Self {
        id.0
    }
}

/// Data transfer object for ApprovalRequest
///
/// This is the public representation of ApprovalRequest for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalRequestDto {
    pub id: ApprovalRequestId,
    pub company_id: Uuid,
    pub resource_type: ApprovalResourceType,
    pub resource_id: Uuid,
    pub policy_id: Option<Uuid>,
    pub requested_by: Uuid,
    pub status: ApprovalStatus,
    pub current_step: Option<i32>,
    pub priority: ApprovalPriority,
    pub submitted_at: Option<DateTime<Utc>>,
    pub decided_at: Option<DateTime<Utc>>,
    pub decided_by: Option<Uuid>,
    pub summary: Option<serde_json::Value>,
    pub metadata: serde_json::Value,
}

/// Summary view of ApprovalRequest for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalRequestSummary {
    pub id: ApprovalRequestId,
    pub status: ApprovalStatus,
}

/// Reference to ApprovalRequest for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalRequestRef {
    pub id: ApprovalRequestId,
}

// ============================================================================
// APPROVALSTEP TYPES
// ============================================================================

/// Type-safe ID for ApprovalStep
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ApprovalStepId(pub Uuid);

impl ApprovalStepId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ApprovalStepId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ApprovalStepId> for Uuid {
    fn from(id: ApprovalStepId) -> Self {
        id.0
    }
}

/// Data transfer object for ApprovalStep
///
/// This is the public representation of ApprovalStep for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalStepDto {
    pub id: ApprovalStepId,
    pub company_id: Uuid,
    pub request_id: Uuid,
    pub step_no: i32,
    pub approver_kind: ApproverKind,
    pub approver_ref: Option<Uuid>,
    pub assigned_to: Uuid,
    pub delegated_from: Option<Uuid>,
    pub status: ApprovalStepStatus,
    pub acted_at: Option<DateTime<Utc>>,
    pub comment: Option<String>,
    pub sla_due_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of ApprovalStep for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalStepSummary {
    pub id: ApprovalStepId,
    pub status: ApprovalStepStatus,
}

/// Reference to ApprovalStep for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalStepRef {
    pub id: ApprovalStepId,
}

// ============================================================================
// APPROVALSTEPTEMPLATE TYPES
// ============================================================================

/// Type-safe ID for ApprovalStepTemplate
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ApprovalStepTemplateId(pub Uuid);

impl ApprovalStepTemplateId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ApprovalStepTemplateId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ApprovalStepTemplateId> for Uuid {
    fn from(id: ApprovalStepTemplateId) -> Self {
        id.0
    }
}

/// Data transfer object for ApprovalStepTemplate
///
/// This is the public representation of ApprovalStepTemplate for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalStepTemplateDto {
    pub id: ApprovalStepTemplateId,
    pub company_id: Uuid,
    pub policy_id: Uuid,
    pub step_no: i32,
    pub approver_kind: ApproverKind,
    pub approver_ref: Option<Uuid>,
    pub sla_hours: Option<i32>,
    pub all_of: Option<serde_json::Value>,
    pub metadata: serde_json::Value,
}

/// Summary view of ApprovalStepTemplate for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalStepTemplateSummary {
    pub id: ApprovalStepTemplateId,
}

/// Reference to ApprovalStepTemplate for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalStepTemplateRef {
    pub id: ApprovalStepTemplateId,
}

// ============================================================================
// DELEGATION TYPES
// ============================================================================

/// Type-safe ID for Delegation
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct DelegationId(pub Uuid);

impl DelegationId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for DelegationId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<DelegationId> for Uuid {
    fn from(id: DelegationId) -> Self {
        id.0
    }
}

/// Data transfer object for Delegation
///
/// This is the public representation of Delegation for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DelegationDto {
    pub id: DelegationId,
    pub company_id: Uuid,
    pub approver_id: Uuid,
    pub delegate_to_id: Uuid,
    pub valid_from: NaiveDate,
    pub valid_to: NaiveDate,
    pub reason: Option<String>,
    pub status: DelegationStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of Delegation for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DelegationSummary {
    pub id: DelegationId,
    pub status: DelegationStatus,
}

/// Reference to Delegation for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DelegationRef {
    pub id: DelegationId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
