//! Approvals Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod application;
pub mod domain;
pub mod exports;
pub mod infrastructure;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::ApprovalPolicyService;
pub use application::service::ApprovalRequestService;
pub use application::service::ApprovalStepService;
pub use application::service::ApprovalStepTemplateService;
pub use application::service::DelegationService;

// Re-exports - Workflows
pub use application::workflows::*;

// <<< CUSTOM
// The guarded composition (operator CRUD + engine reads + decide/withdraw verbs).
pub use presentation::http::guarded_routes::{
    create_guarded_approvals_routes, create_guarded_approvals_routes_with,
};
// END CUSTOM

use axum::Router;
use sqlx::PgPool;
use std::sync::Arc;

/// Approvals module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let approvals = ApprovalsModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = approvals.all_crud_routes();
/// ```
pub struct ApprovalsModule {
    pub(crate) approval_policy_service: Arc<ApprovalPolicyService>,
    pub(crate) approval_request_service: Arc<ApprovalRequestService>,
    pub(crate) approval_step_service: Arc<ApprovalStepService>,
    pub(crate) approval_step_template_service: Arc<ApprovalStepTemplateService>,
    pub(crate) delegation_service: Arc<DelegationService>,
    // <<< CUSTOM FIELDS
    // The decision engine (file/decide/status/withdraw). Default resolver is fail-closed:
    // dynamic approver kinds need the host to supply one at composition time.
    pub(crate) approvals_write_service: Arc<application::service::ApprovalsWriteService>,
    // END CUSTOM
}

impl ApprovalsModule {
    /// Create a new module builder
    pub fn builder() -> ApprovalsModuleBuilder {
        ApprovalsModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_approval_policy_routes, create_approval_request_routes,
            create_approval_step_routes, create_approval_step_template_routes,
            create_delegation_routes,
        };

        Router::new()
            .merge(create_approval_policy_routes(
                self.approval_policy_service.clone(),
            ))
            .merge(create_approval_request_routes(
                self.approval_request_service.clone(),
            ))
            .merge(create_approval_step_routes(
                self.approval_step_service.clone(),
            ))
            .merge(create_approval_step_template_routes(
                self.approval_step_template_service.clone(),
            ))
            .merge(create_delegation_routes(self.delegation_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(
        note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface"
    )]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_approval_policy_read_routes, create_approval_request_read_routes,
            create_approval_step_read_routes, create_approval_step_template_read_routes,
            create_delegation_read_routes,
        };

        Router::new()
            .merge(create_approval_policy_read_routes(
                self.approval_policy_service.clone(),
            ))
            .merge(create_approval_request_read_routes(
                self.approval_request_service.clone(),
            ))
            .merge(create_approval_step_read_routes(
                self.approval_step_service.clone(),
            ))
            .merge(create_approval_step_template_read_routes(
                self.approval_step_template_service.clone(),
            ))
            .merge(create_delegation_read_routes(
                self.delegation_service.clone(),
            ))
    }

    // <<< CUSTOM METHODS
    /// The decision engine held by this module (default fail-closed resolver).
    pub fn approvals_write_service(&self) -> Arc<application::service::ApprovalsWriteService> {
        self.approvals_write_service.clone()
    }

    /// Replace the engine at the composition root — the way a host supplies a real
    /// approver resolver for the dynamic kinds. Call before mounting routes; the module is
    /// consumed once at startup.
    pub fn with_approvals_write_service(
        mut self,
        svc: Arc<application::service::ApprovalsWriteService>,
    ) -> Self {
        self.approvals_write_service = svc;
        self
    }
    // END CUSTOM
}

/// Builder for ApprovalsModule
pub struct ApprovalsModuleBuilder {
    db_pool: Option<PgPool>,
}

impl ApprovalsModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self { db_pool: None }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<ApprovalsModule> {
        let db_pool = self
            .db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // ApprovalPolicy service
        let approval_policy_repository = Arc::new(ApprovalPolicyRepository::new(db_pool.clone()));
        let approval_policy_service = Arc::new(ApprovalPolicyService::with_repository(
            approval_policy_repository.clone(),
        ));

        // ApprovalRequest service
        let approval_request_repository = Arc::new(ApprovalRequestRepository::new(db_pool.clone()));
        let approval_request_service = Arc::new(ApprovalRequestService::with_repository(
            approval_request_repository.clone(),
        ));

        // ApprovalStep service
        let approval_step_repository = Arc::new(ApprovalStepRepository::new(db_pool.clone()));
        let approval_step_service = Arc::new(ApprovalStepService::with_repository(
            approval_step_repository.clone(),
        ));

        // ApprovalStepTemplate service
        let approval_step_template_repository =
            Arc::new(ApprovalStepTemplateRepository::new(db_pool.clone()));
        let approval_step_template_service = Arc::new(
            ApprovalStepTemplateService::with_repository(approval_step_template_repository.clone()),
        );

        // Delegation service
        let delegation_repository = Arc::new(DelegationRepository::new(db_pool.clone()));
        let delegation_service = Arc::new(DelegationService::with_repository(
            delegation_repository.clone(),
        ));

        // <<< CUSTOM
        let approvals_write_service = Arc::new(application::service::ApprovalsWriteService::new(
            db_pool.clone(),
        ));
        // END CUSTOM

        Ok(ApprovalsModule {
            approval_policy_service,
            approval_request_service,
            approval_step_service,
            approval_step_template_service,
            delegation_service,
            // <<< CUSTOM
            approvals_write_service,
            // END CUSTOM
        })
    }
}

impl Default for ApprovalsModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
