//! Use case type aliases for ApprovalStep aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateApprovalStepDto, UpdateApprovalStepDto};
use crate::application::service::ApprovalStepService;
use crate::domain::entity::ApprovalStep;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateApprovalStepUseCase = CreateUseCase<ApprovalStep, CreateApprovalStepDto, ApprovalStepService>;
pub type UpdateApprovalStepUseCase = UpdateUseCase<ApprovalStep, UpdateApprovalStepDto, ApprovalStepService>;
pub type GetApprovalStepUseCase    = GetUseCase<ApprovalStep, ApprovalStepService>;
pub type DeleteApprovalStepUseCase = DeleteUseCase<ApprovalStep, ApprovalStepService>;
pub type ListApprovalStepUseCase   = ListUseCase<ApprovalStep, ApprovalStepService>;

// <<< CUSTOM
// END CUSTOM
