//! Use case type aliases for ApprovalStepTemplate aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateApprovalStepTemplateDto, UpdateApprovalStepTemplateDto};
use crate::application::service::ApprovalStepTemplateService;
use crate::domain::entity::ApprovalStepTemplate;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateApprovalStepTemplateUseCase = CreateUseCase<ApprovalStepTemplate, CreateApprovalStepTemplateDto, ApprovalStepTemplateService>;
pub type UpdateApprovalStepTemplateUseCase = UpdateUseCase<ApprovalStepTemplate, UpdateApprovalStepTemplateDto, ApprovalStepTemplateService>;
pub type GetApprovalStepTemplateUseCase    = GetUseCase<ApprovalStepTemplate, ApprovalStepTemplateService>;
pub type DeleteApprovalStepTemplateUseCase = DeleteUseCase<ApprovalStepTemplate, ApprovalStepTemplateService>;
pub type ListApprovalStepTemplateUseCase   = ListUseCase<ApprovalStepTemplate, ApprovalStepTemplateService>;

// <<< CUSTOM
// END CUSTOM
