//! Use case type aliases for ApprovalPolicy aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateApprovalPolicyDto, UpdateApprovalPolicyDto};
use crate::application::service::ApprovalPolicyService;
use crate::domain::entity::ApprovalPolicy;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateApprovalPolicyUseCase = CreateUseCase<ApprovalPolicy, CreateApprovalPolicyDto, ApprovalPolicyService>;
pub type UpdateApprovalPolicyUseCase = UpdateUseCase<ApprovalPolicy, UpdateApprovalPolicyDto, ApprovalPolicyService>;
pub type GetApprovalPolicyUseCase    = GetUseCase<ApprovalPolicy, ApprovalPolicyService>;
pub type DeleteApprovalPolicyUseCase = DeleteUseCase<ApprovalPolicy, ApprovalPolicyService>;
pub type ListApprovalPolicyUseCase   = ListUseCase<ApprovalPolicy, ApprovalPolicyService>;

// <<< CUSTOM
// END CUSTOM
