//! Use case type aliases for ApprovalRequest aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateApprovalRequestDto, UpdateApprovalRequestDto};
use crate::application::service::ApprovalRequestService;
use crate::domain::entity::ApprovalRequest;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateApprovalRequestUseCase = CreateUseCase<ApprovalRequest, CreateApprovalRequestDto, ApprovalRequestService>;
pub type UpdateApprovalRequestUseCase = UpdateUseCase<ApprovalRequest, UpdateApprovalRequestDto, ApprovalRequestService>;
pub type GetApprovalRequestUseCase    = GetUseCase<ApprovalRequest, ApprovalRequestService>;
pub type DeleteApprovalRequestUseCase = DeleteUseCase<ApprovalRequest, ApprovalRequestService>;
pub type ListApprovalRequestUseCase   = ListUseCase<ApprovalRequest, ApprovalRequestService>;

// <<< CUSTOM
// END CUSTOM
