//! Use case type aliases for Delegation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateDelegationDto, UpdateDelegationDto};
use crate::application::service::DelegationService;
use crate::domain::entity::Delegation;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateDelegationUseCase = CreateUseCase<Delegation, CreateDelegationDto, DelegationService>;
pub type UpdateDelegationUseCase = UpdateUseCase<Delegation, UpdateDelegationDto, DelegationService>;
pub type GetDelegationUseCase    = GetUseCase<Delegation, DelegationService>;
pub type DeleteDelegationUseCase = DeleteUseCase<Delegation, DelegationService>;
pub type ListDelegationUseCase   = ListUseCase<Delegation, DelegationService>;

// <<< CUSTOM
// END CUSTOM
