//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod approval_policy_usecases;
pub mod approval_request_usecases;
pub mod approval_step_usecases;
pub mod approval_step_template_usecases;
pub mod delegation_usecases;

pub use approval_policy_usecases::{
    CreateApprovalPolicyUseCase, UpdateApprovalPolicyUseCase, GetApprovalPolicyUseCase,
    DeleteApprovalPolicyUseCase, ListApprovalPolicyUseCase,
};
pub use approval_request_usecases::{
    CreateApprovalRequestUseCase, UpdateApprovalRequestUseCase, GetApprovalRequestUseCase,
    DeleteApprovalRequestUseCase, ListApprovalRequestUseCase,
};
pub use approval_step_usecases::{
    CreateApprovalStepUseCase, UpdateApprovalStepUseCase, GetApprovalStepUseCase,
    DeleteApprovalStepUseCase, ListApprovalStepUseCase,
};
pub use approval_step_template_usecases::{
    CreateApprovalStepTemplateUseCase, UpdateApprovalStepTemplateUseCase, GetApprovalStepTemplateUseCase,
    DeleteApprovalStepTemplateUseCase, ListApprovalStepTemplateUseCase,
};
pub use delegation_usecases::{
    CreateDelegationUseCase, UpdateDelegationUseCase, GetDelegationUseCase,
    DeleteDelegationUseCase, ListDelegationUseCase,
};

// <<< CUSTOM
// END CUSTOM
