//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod approval_policy_handler;
pub mod approval_request_handler;
pub mod approval_step_handler;
pub mod approval_step_template_handler;
pub mod delegation_handler;

// <<< CUSTOM
// The guarded composition (operator CRUD + engine reads + decide/withdraw verbs).
// Hand-authored (see metaphor.codegen.yaml user_owned).
pub mod guarded_routes;
pub use guarded_routes::{
    create_guarded_approvals_routes, create_guarded_approvals_routes_with,
    create_operator_master_data_routes,
};
// END CUSTOM

// Re-exports
pub use approval_policy_handler::{create_approval_policy_routes, create_approval_policy_read_routes, create_approval_policy_write_routes};
pub use approval_request_handler::{create_approval_request_routes, create_approval_request_read_routes, create_approval_request_write_routes};
pub use approval_step_handler::{create_approval_step_routes, create_approval_step_read_routes, create_approval_step_write_routes};
pub use approval_step_template_handler::{create_approval_step_template_routes, create_approval_step_template_read_routes, create_approval_step_template_write_routes};
pub use delegation_handler::{create_delegation_routes, create_delegation_read_routes, create_delegation_write_routes};
// <<< CUSTOM
// END CUSTOM
